### ISSUE TITLE
Cannot unpack compressed files after spooling (due to incorrect header size?)

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#10]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/10) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

```
#!Traceback

Traceback (most recent call last):
  File "/home/aeb85/anaconda2/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16763, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/DSView/dsviewer.py", line 395, in LoadData
    im = ImageStack(filename=args[0], queueURI=options.queueURI, mdh=options.metadata)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/image.py", line 138, in __init__
    self.Load(filename)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/image.py", line 788, in Load
    self.LoadClusterPZF(filename)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/image.py", line 401, in LoadClusterPZF
    self.data = BGSDataSource.DataSource(self.dataSource) #this will get replaced with a wrapped version
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/DataSources/BGSDataSource.py", line 223, in __init__
    self.bBufferMn = backgroundBuffer(self.dBuffer)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/DataSources/BGSDataSource.py", line 65, in __init__
    self.curBG = np.zeros(dataBuffer.dataSource.getSliceShape(), 'f4')
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/DataSources/ClusterPZFDataSource.py", line 77, in getSliceShape
    self.fshape = self.getSlice(0).shape
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/DataSources/ClusterPZFDataSource.py", line 70, in getSlice
    sl = PZFFormat.loads(clusterIO.getFile(frameName, self.clusterfilter))[0]
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/PZFFormat.py", line 272, in loads
    data = data.view(DATA_FMTS[header['DataFormat']]).reshape([w,h,d])
ValueError: total size of new array must be unchanged
```

Note that LoadClusterPZF works if file on the client computer was not compressed during spooling.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Fixed in repository head

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Fixed in repository head.
