### ISSUE TITLE
Cannot open .mat files in VisGUI on Python3

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#101]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/101) by Anonymous.**

----------------------------------------

```
#!python

Traceback (most recent call last):
  File "/anaconda3/envs/pyme/lib/python3.6/site-packages/wx/core.py", line 2228, in Notify
    self.notify()
  File "/anaconda3/envs/pyme/lib/python3.6/site-packages/wx/core.py", line 3384, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/visCore.py", line 650, in _create_base_layer
    l = self.add_pointcloud_layer(method='points')
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/visCore.py", line 415, in add_pointcloud_layer
    l = PointCloudRenderLayer(self.pipeline, method=method, dsname=ds_name, **kwargs)
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 129, in __init__
    self._set_method()
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 147, in _set_method
    self.update()
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 169, in update
    self.update_from_datasource(self.datasource)
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 199, in update_from_datasource
    self.update_data(x, y, z, c, cmap=getattr(cm, self.cmap), clim=self.clim, alpha=self.alpha)
  File "/Users/zachcm/Code/python-microscopy/PYME/LMVis/layers/pointcloud.py", line 227, in update_data
    cs[:, 3] = alpha
IndexError: index 3 is out of bounds for axis 1 with size 1
```

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

I made this issue. I was not logged in, apologies.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Figured as much - this is really odd - have you tried changing the point colour?

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

It’s super weird. I’m using a .mat file that only has columns x,y,z. There is no other data. I can’t change the point color because the layer won’t add to VisGUI.

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

I get an identical traceback on my Windows install of PYME.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Issue was that `loadmat()` generated Nx1 2D arrays for each column rather than 1D arrays, should be fixed in most recent head.

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

That seems to have fixed it! Weirdly, take a snapshot has disappeared, though.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Take a snapshot disappeared as it was broken on python3 and/or recent versions of scipy \(relies on an obscure deprecated scipy call\) and prevented VisGUI from loading. I thought removing \(if temporary\) was preferable to having to work out which versions of scipy work and adding another pin / dependency resolution issue.

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

Makes sense.
