### ISSUE TITLE
[ENHANCEMENT] more null object patterning

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1010]
**Is your feature request related to a problem? Please describe.**
As discussed yesterday, sometimes it can be nice to have _a_ result file even if it is null, e.g. #1009. Wanted to crack open an issue for it so we can discuss other places where it might be helpful. At the moment, I have next hit it in `PYME.IO.tabular`

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-24-038ad8a614fa> in <module>
      8         #with unifiedIO.local_or_temp_filename('pyme-cluster:///' + r) as fn:
      9         hdf = h5rFile.openH5R(r)
---> 10         ds = tabular.HDFSource(hdf, 'measured_gmm')
     11         ds = tabular.MappingFilter(ds)
     12         ds.addColumn('file', np.array([r for ind in range(len(ds))]))

~/code/python-microscopy/PYME/IO/tabular.py in __init__(self, h5fFile, tablename)
    481 
    482     def __init__(self, h5fFile, tablename='FitResults'):
--> 483         BaseHDFSource.__init__(self, h5fFile, tablename)
    484         #or shorter aliases
    485 

~/code/python-microscopy/PYME/IO/tabular.py in __init__(self, h5fFile, tablename)
    428                 self.fitResults = h5f.getTableData(tablename, slice(None))
    429                 if (len(self.fitResults) == 0):
--> 430                     raise RuntimeError('Was expecting to find a "%s" table' % tablename)
    431 
    432                 #allow access using unnested original names

RuntimeError: Was expecting to find a "measured_gmm" table

```

for

```
/ (RootGroup) ''
/measured_gmm (Table(0,), shuffle, zlib(5)) ''
  description := {
  "count": Int32Col(shape=(), dflt=0, pos=0),
  "x": Float32Col(shape=(), dflt=0.0, pos=1),
  "y": Float32Col(shape=(), dflt=0.0, pos=2),
  "z": Float32Col(shape=(), dflt=0.0, pos=3),
  "gyrationRadius": Float32Col(shape=(), dflt=0.0, pos=4),
  "median_abs_deviation": Float32Col(shape=(), dflt=0.0, pos=5),
  "axis0": Float32Col(shape=(3,), dflt=0.0, pos=6),
  "axis1": Float32Col(shape=(3,), dflt=0.0, pos=7),
  "axis2": Float32Col(shape=(3,), dflt=0.0, pos=8),
  "sigma0": Float32Col(shape=(), dflt=0.0, pos=9),
  "sigma1": Float32Col(shape=(), dflt=0.0, pos=10),
  "sigma2": Float32Col(shape=(), dflt=0.0, pos=11),
  "sigma_x": Float32Col(shape=(), dflt=0.0, pos=12),
  "sigma_y": Float32Col(shape=(), dflt=0.0, pos=13),
  "sigma_z": Float32Col(shape=(), dflt=0.0, pos=14),
  "anisotropy": Float32Col(shape=(), dflt=0.0, pos=15),
  "theta": Float32Col(shape=(), dflt=0.0, pos=16),
  "phi": Float32Col(shape=(), dflt=0.0, pos=17)}
  byteorder := 'little'
  chunkshape := (1365,)

```

**Comment by barentine** [comment]
Potentially another spot in get_labels_from_image
```
Traceback:
----------
Traceback (most recent call last):
  File "/home/ubuntu/code/python-microscopy/PYME/cluster/taskWorkerHTTP.py", line 341, in computeLoop
    recipe.execute()
  File "/home/ubuntu/code/python-microscopy/PYME/recipes/base.py", line 749, in execute
    m.execute(self.namespace)
  File "/home/ubuntu/code/python-microscopy/PYME/recipes/localisations.py", line 600, in execute
    ids, numPerObject = cluster_morphology.get_labels_from_image(img, inp, minimum_localizations=self.minimum_localizations)
  File "/home/ubuntu/code/python-microscopy/PYME/Analysis/points/cluster_morphology.py", line 70, in get_labels_from_image
    numPerObject, b = np.histogram(ids, np.arange(ids.max() + 1.5) + .5)
  File "/home/ubuntu/miniconda3/lib/python3.6/site-packages/numpy/core/_methods.py", line 39, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity```

**Comment by barentine** [comment]
another in mapping
```
Traceback:
----------
Traceback (most recent call last):
  File "/home/ubuntu/code/python-microscopy/PYME/cluster/taskWorkerHTTP.py", line 341, in computeLoop
    recipe.execute()
  File "/home/ubuntu/code/python-microscopy/PYME/recipes/base.py", line 749, in execute
    m.execute(self.namespace)
  File "/home/ubuntu/code/python-microscopy/PYME/recipes/localisations.py", line 603, in execute
    labeled.addColumn(self.label_key_name, ids)
  File "/home/ubuntu/code/python-microscopy/PYME/IO/tabular.py", line 1001, in addColumn
    if not len(values) == len(self.resultsSource[list(self.resultsSource.keys())[0]]):
TypeError: len() of unsized object

```
