### ISSUE TITLE
pzf support for more data types

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#102]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/102) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

When trying to run analysis with camera maps as h5 \(tiff saving on py3 wasn’t functional at the time I \(re\)generated them.

![](https://bitbucket.org/repo/kAoqj6/images/2430373180-image.png)
![](https://bitbucket.org/repo/kAoqj6/images/4107175868-image.png)
running with python-microscopy=19.11.13

Confirming by trying to load through dh5view:

‌

```
$ dh5view pyme-cluster:///CALIBRATION/htsms_800Hz_dark_1ms.h5
No handlers could be found for logger "/home/smeagol/code/python-microscopy/PYME/config.pyc"
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
Starting main loop
Loading data
filename == pyme-cluster:///CALIBRATION/htsms_800Hz_dark_1ms.h5
ERROR:PYME.IO.clusterIO:Timeout on get file
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/IO/clusterIO.py", line 648, in getFile
    r = s.get(url, timeout=.5)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',))
INFO:PYME.IO.clusterIO:2 retries left
ERROR:PYME.IO.clusterIO:Timeout on get file
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/IO/clusterIO.py", line 648, in getFile
    r = s.get(url, timeout=.5)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='10.150.7.9', port=8080): Read timed out. (read timeout=0.5)
INFO:PYME.IO.clusterIO:1 retries left
ERROR:PYME.IO.clusterIO:Timeout on get file
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/IO/clusterIO.py", line 648, in getFile
    r = s.get(url, timeout=.5)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='10.150.7.9', port=8080): Read timed out. (read timeout=0.5)
INFO:PYME.IO.clusterIO:0 retries left
Traceback (most recent call last):
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16763, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/smeagol/code/python-microscopy/PYME/DSView/dsviewer.py", line 423, in LoadData
    im = ImageStack(filename=args[0], queueURI=options.queueURI, mdh=options.metadata)
  File "/home/smeagol/code/python-microscopy/PYME/IO/image.py", line 224, in __init__
    self.Load(filename, prompt=load_prompt)
  File "/home/smeagol/code/python-microscopy/PYME/IO/image.py", line 1002, in Load
    self._loadClusterPZF(filename)
  File "/home/smeagol/code/python-microscopy/PYME/IO/image.py", line 516, in _loadClusterPZF
    self.data = BGSDataSource.DataSource(self.dataSource) #this will get replaced with a wrapped version
  File "/home/smeagol/code/python-microscopy/PYME/IO/DataSources/BGSDataSource.py", line 225, in __init__
    self.bBufferMn = backgroundBuffer(self.dBuffer)
  File "/home/smeagol/code/python-microscopy/PYME/IO/DataSources/BGSDataSource.py", line 67, in __init__
    self.curBG = np.zeros(dataBuffer.dataSource.getSliceShape(), 'f4')
  File "/home/smeagol/code/python-microscopy/PYME/IO/DataSources/ClusterPZFDataSource.py", line 78, in getSliceShape
    self.fshape = self.getSlice(0).shape
  File "/home/smeagol/code/python-microscopy/PYME/IO/DataSources/ClusterPZFDataSource.py", line 71, in getSlice
    sl = PZFFormat.loads(clusterIO.getFile(frameName, self.clusterfilter))[0]
  File "/home/smeagol/code/python-microscopy/PYME/IO/clusterIO.py", line 648, in getFile
    r = s.get(url, timeout=.5)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPConnectionPool(host='10.150.7.9', port=8080): Read timed out. (read timeout=0.5)
```

Data turns out to be float64. Problem is likely that I sftp’d the camera maps rather than spooling them.

Could be nice if we could dump more formats such that any h5 on the cluster would suffice. That said, for the GPu stuff we cast everything to float32 anyway

‌

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Note that I was able to simply open the camera maps \(as h5\) on my local machine, see that the EArray atom was float64, but since the `PYME.IO.DataSources.BGSDataSource.DataSource` casts to float32 I could simply save as h5 again and the resulting file has atom of float32, which then works on the cluster

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Hmm - this specifically relates to how clusterIO “looks into” .h5 files. This mainly exists as a hack to allow the cluster spooling framework to be used on windows where lots of files in a directory don’t work very well. Your usage is also a hack around the previous issues with .tif on py3. The canonical format for camera maps is .tif, and we generally don’t expect anything except other than raw localization image data \(uint16 or compressed as pzf\) to have a .h5 extension \(the .h5 = raw localization image series logic is what is catching you out here\).

There might be some merit to expanding our .h5 image support \(although if we do this we should really also go to more than xyt\), and to expanding .pzf to encompass all common numpy types, but this has the potential to get really hacky

* There are a lot of places where we assume that .h5 means a sequence of raw images
* .pzf was designed as a minimal, ‘lightweight’, high-performance format and adding support for more datatypes risks loosing some of these advantages
* The main rationale for .pzf \(as opposed to other formats\) is as a container for data compressed with our custom compression algorithm. This algorithm won’t work well / at all with floating point data. I’m not entirely sure why I added float32 in the first place
* At this point I don’t see a rationale for ever saving image data as double - although we could fairly easily add support to pzf, where do we stop? Should we also allow u4, u8, i1, i2, i4, i8, complex types, etc …? We don’t really want to replicate the numpy .npy dump format. 
* Related to this, the bug is arguably generating double precision images \(and letting them be saved as .h5\) in the first place.

I’m not saying that we shouldn’t expand the data types but that it needs careful consideration. Likewise, if we are making the format more generic, we need to think about things like endianess 

‌
