### ISSUE TITLE
[BUG] something with the new datasource wrapping

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1030]
**Describe the bug**

**To Reproduce**
1. update
2. wish you hadn't

```
===========================================================================
Error in rule: 000000-b850b3ff1a5f4df0a5455a5b5a478cf2 running task: 0 on lechiffre:19305

taskDescr:
----------
{'id': '000000-b850b3ff1a5f4df0a5455a5b5a478cf2~0', 'type': 'recipe', 'inputs': {'input': 'pyme-cluster://villains/Bergamot/2021_2_16/EMC0105H/mapped/17_2_series_CN_mapped.hdf'}, 'output_dir': 'pyme-cluster://villains/Bergamot/2021_2_16/EMC0105H/shell-kde-gmm/', 'taskdef': {'recipe': "- localisations.DensityMapping:\n    colours:\n    - chan0\n    inputLocalizations: mapped\n    jitterScale: 30.0\n    outputImage: jt2d\n    pixelSize: 40.0\n    renderingModule: Gaussian\n- processing.Threshold:\n    inputName: smoothed\n    method: otsu\n    outputName: thresholded\n    processFramesIndividually: false\n- processing.Label:\n    inputName: thresholded\n    minRegionPixels: 1\n    outputName: labeled\n- processing.SelectLargestLabel:\n    inputName: labeled\n    outputName: nucleus\n- processing.BinaryDilation:\n    inputName: nucleus\n    iterations: 10\n    outputName: mask\n    processFramesIndividually: false\n- localisations.LabelsFromImage:\n    inputImage: mask\n    inputName: mapped\n    outputName: labeled_points\n- tablefilters.FilterTable:\n    filters:\n      objectID:\n      - 0.5\n      - 1.5\n    inputName: labeled_points\n    outputName: inside_nucleus_mask\n- localisations.ExtractTableChannel:\n    channel: chan0\n    inputName: inside_nucleus_mask\n    outputName: lamin\n- surface_fitting.SphericalHarmonicShell:\n    input_name: lamin\n    output_name: harmonic_shell\n    output_name_mapped: lamin_shell_mapped\n- surface_fitting.AddSphericalHarmonicShellMappedCoords:\n    input_localizations: inside_nucleus_mask\n    input_shell: harmonic_shell\n    output_mapped: shell_mapped\n- output.HDFOutput:\n    filePattern: '{output_dir}/{file_stub}_spharm-gmm-ripleys.hdf'\n    inputVariables:\n      gmm_labeled: gmm_labeled\n      harmonic_shell: harmonic_shell\n      measured_gmm: measured_gmm\n      r_uniform_kde: r_uniform_kde\n      shell_mapped: shell_mapped\n    scheme: pyme-cluster://\n- filters.MaxFilter:\n    inputName: jt2d\n    outputName: smoothed\n    processFramesIndividually: false\n    sizeX: 15\n    sizeY: 15\n    sizeZ: 1\n- localisations.ExtractTableChannel:\n    channel: chan1\n    inputName: shell_mapped\n    outputName: mapped_coilin\n- pointcloud.GaussianMixtureModel:\n    input_points: mapped_coilin\n    mode: bic\n    n: 50\n    output_labeled: gmm_labeled\n- tablefilters.FilterTable:\n    filters:\n      gmm_label_log_prob:\n      - -26.0\n      - 0.0\n    inputName: gmm_labeled\n    outputName: filtered_clusters\n- localisations.MeasureClusters3D:\n    inputName: filtered_clusters\n    labelKey: gmm_label\n    outputName: measured_gmm\n- output.ImageOutput:\n    filePattern: '{output_dir}/{file_stub}_nucleus_mask.h5'\n    inputName: mask\n    scheme: pyme-cluster://\n- surface_fitting.SHShellRadiusDensityEstimate:\n    input_shell: harmonic_shell\n    output: r_uniform_kde\n    r_bin_spacing: 0.02\n    sampling_nm:\n    - 200.0\n    - 200.0\n    - 200.0\n"}}

Traceback:
----------
Traceback (most recent call last):
  File "/home/ubuntu/code/python-microscopy/PYME/cluster/taskWorkerHTTP.py", line 342, in computeLoop
    recipe.execute()
  File "/home/ubuntu/code/python-microscopy/PYME/recipes/recipe.py", line 203, in execute
    m.execute(self.namespace)
  File "/home/ubuntu/code/python-microscopy/PYME/recipes/base.py", line 649, in execute
    namespace[self.outputName] = self.filter(namespace[self.inputName])
  File "/home/ubuntu/code/python-microscopy/PYME/recipes/base.py", line 617, in filter
    data = image.data_xyztc[:, :, :, t, c].squeeze().astype('f')
  File "/home/ubuntu/code/python-microscopy/PYME/IO/dataWrap.py", line 87, in __getitem__
    return self.wrapList[kL].__getitem__(keys[:self.listDim])
  File "/home/ubuntu/code/python-microscopy/PYME/IO/dataWrap.py", line 87, in __getitem__
    return self.wrapList[kL].__getitem__(keys[:self.listDim])
  File "/home/ubuntu/code/python-microscopy/PYME/IO/dataWrap.py", line 85, in __getitem__
    return np.concatenate([self.wrapList[i].__getitem__(keys[:self.listDim]) for i in range(*kL.indices(len(self.wrapList)))], self.listDim)
  File "<__array_function__ internals>", line 6, in concatenate
numpy.AxisError: axis 2 is out of bounds for array of dimension 2


```

**Expected behavior**

**Screenshots**

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10]
 - Python version:
 - numpy version:
 - wxpython version [if a UI bug]:

**Additional context**

**Comment by David-Baddeley** [comment]
Could you send the recipe - I suspect it's a 2D image issue. Will get onto it promptly

**Comment by David-Baddeley** [comment]
Hmm - definitely need the recipe. Can't reproduce on a simple 2D image.

**Comment by barentine** [comment]
recipe is posted above in the rule
```
- localisations.DensityMapping:
    colours:
    - chan0
    inputLocalizations: mapped
    jitterScale: 30.0
    outputImage: jt2d
    pixelSize: 40.0
    renderingModule: Gaussian
- processing.Threshold:
    inputName: smoothed
    method: otsu
    outputName: thresholded
    processFramesIndividually: false
- processing.Label:
    inputName: thresholded
    minRegionPixels: 1
    outputName: labeled
- processing.SelectLargestLabel:
    inputName: labeled
    outputName: nucleus
- processing.BinaryDilation:
    inputName: nucleus
    iterations: 10
    outputName: mask
    processFramesIndividually: false
- localisations.LabelsFromImage:
    inputImage: mask
    inputName: mapped
    outputName: labeled_points
- tablefilters.FilterTable:
    filters:
      objectID:
      - 0.5
      - 1.5
    inputName: labeled_points
    outputName: inside_nucleus_mask
- localisations.ExtractTableChannel:
    channel: chan0
    inputName: inside_nucleus_mask
    outputName: lamin
- surface_fitting.SphericalHarmonicShell:
    input_name: lamin
    output_name: harmonic_shell
    output_name_mapped: lamin_shell_mapped
- surface_fitting.AddSphericalHarmonicShellMappedCoords:
    input_localizations: inside_nucleus_mask
    input_shell: harmonic_shell
    output_mapped: shell_mapped
- output.HDFOutput:
    filePattern: '{output_dir}/{file_stub}_spharm-gmm-ripleys.hdf'
    inputVariables:
      gmm_labeled: gmm_labeled
      harmonic_shell: harmonic_shell
      measured_gmm: measured_gmm
      r_uniform_kde: r_uniform_kde
      shell_mapped: shell_mapped
    scheme: pyme-cluster://
- filters.MaxFilter:
    inputName: jt2d
    outputName: smoothed
    processFramesIndividually: false
    sizeX: 15
    sizeY: 15
    sizeZ: 1
- localisations.ExtractTableChannel:
    channel: chan1
    inputName: shell_mapped
    outputName: mapped_coilin
- pointcloud.GaussianMixtureModel:
    input_points: mapped_coilin
    mode: bic
    n: 50
    output_labeled: gmm_labeled
- tablefilters.FilterTable:
    filters:
      gmm_label_log_prob:
      - -26.0
      - 0.0
    inputName: gmm_labeled
    outputName: filtered_clusters
- localisations.MeasureClusters3D:
    inputName: filtered_clusters
    labelKey: gmm_label
    outputName: measured_gmm
- output.ImageOutput:
    filePattern: '{output_dir}/{file_stub}_nucleus_mask.h5'
    inputName: mask
    scheme: pyme-cluster://
- surface_fitting.SHShellRadiusDensityEstimate:
    input_shell: harmonic_shell
    output: r_uniform_kde
    r_bin_spacing: 0.02
    sampling_nm:
    - 200.0
    - 200.0
    - 200.0
```

**Comment by David-Baddeley** [comment]
Have a candidate fix based on the traceback alone. Fix is untested apart from not breaking existing uses, and potentially a bit of a shot in the dark.

**Comment by David-Baddeley** [comment]
I can reproduce the error with a pruned down recipe (and patch in place :():

```yaml
- localisations.AddPipelineDerivedVars:
    inputEvents: ''
    inputFitResults: FitResults
    outputLocalizations: Localizations
- localisations.ProcessColour:
    input: Localizations
    output: colour_mapped
- tablefilters.FilterTable:
    filters:
      A:
      - 5
      - 20000
      error_x:
      - 0
      - 30
      error_y:
      - 0
      - 30
      sig:
      - 95
      - 200
    inputName: colour_mapped
    outputName: filtered_localizations
- localisations.DensityMapping:
    inputLocalizations: filtered_localizations
    jitterVariable: error_x
    outputImage: grend
    pixelSize: 50.0
    renderingModule: Gaussian
- processing.Threshold:
    dimensionality: XYZ
    inputName: smoothed
    method: otsu
    outputName: thresholded
- processing.Label:
    inputName: thresholded
    minRegionPixels: 1
    outputName: labeled
- processing.SelectLargestLabel:
    inputName: labeled
    outputName: nucleus
- processing.BinaryDilation:
    dimensionality: XYZ
    inputName: nucleus
    iterations: 10
    outputName: mask
- filters.MaxFilter:
    dimensionality: XYZ
    inputName: grend
    outputName: smoothed
    sizeX: 15
    sizeY: 15
    sizeZ: 1
- output.ImageOutput:
    filePattern: '{output_dir}/{file_stub}.tif'
    inputName: mask
```

**Comment by David-Baddeley** [comment]
#1031 now fixes the original error, but there's a new one in ImageOutput.

**Comment by David-Baddeley** [comment]
The image output error is now fixed (was specific to binary masks, so may not have impacted you anyway).

**Comment by barentine** [comment]
Thanks @David-Baddeley !
