### ISSUE TITLE
[BUG] error when trying to acquire camera frames without cluster running

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#1141]
**Describe the bug**
If the cluster is not running I get an error when trying to take any image when the acqusition code is trying to access maps.

**To Reproduce**
1. Start `PYMEAcquire`
2. **Don't run a cluster**
3. Try to acquire an image (e.g. Snapshot `F5`)

**Expected behavior**
Ideally would work if somebody is trying local File mode acquisitions.

**Error message with version info**

```
 Error whilst running Acquire>Snapshot	F5
==============================================
python-microscopy=21.09.23
python=3.7.11, platform=win32
numpy=1.19.2, wx=4.0.4 msw (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "c:\python-support-files\pyme-py37\PYME\Acquire\Hardware\Camera.py", line 87, in _fill_camera_map_id
    map_fn = self._camera_map_cache[cache_key]
KeyError: ('dark', 'VSC-02858', 0.1000032)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python-support-files\pyme-py37\PYME\IO\cluster_directory.py", line 275, in locate_file
    locs, t = self._locateCache[filename]
KeyError: 'CALIBRATION/VSC-02858/dark_100ms.tif'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python-support-files\pyme-py37\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "c:\python-support-files\pyme-py37\PYME\Acquire\acquiremainframe.py", line 486, in OnMAquireOnePic
    mdgen(mdh)
  File "c:\python-support-files\pyme-py37\PYME\Acquire\Hardware\AndorNeo\AndorZyla.py", line 644, in GenStartMetadata
    self.fill_camera_map_metadata(mdh)
  File "c:\python-support-files\pyme-py37\PYME\Acquire\Hardware\Camera.py", line 96, in fill_camera_map_metadata
    self._fill_camera_map_id(mdh, 'Camera.DarkMapID', map_type='dark')
  File "c:\python-support-files\pyme-py37\PYME\Acquire\Hardware\Camera.py", line 89, in _fill_camera_map_id
    map_fn = check_mapexists(mdh, map_type, fill=False)
  File "c:\python-support-files\pyme-py37\PYME\Acquire\Hardware\Camera.py", line 60, in check_mapexists
    if clusterIO.exists(cluster_path):
  File "c:\python-support-files\pyme-py37\PYME\IO\clusterIO.py", line 265, in exists
    return get_dir_manager(serverfilter).exists(name)
  File "c:\python-support-files\pyme-py37\PYME\IO\cluster_directory.py", line 397, in exists
    return (len(self.locate_file(name, True)) > 0) or self.isdir(name)
  File "c:\python-support-files\pyme-py37\PYME\IO\cluster_directory.py", line 284, in locate_file
    for s in self.dataservers:
  File "c:\python-support-files\pyme-py37\PYME\IO\cluster_directory.py", line 159, in dataservers
    raise IOError('No data servers found, is the cluster running?')
OSError: No data servers found, is the cluster running?
```

**Comment by David-Baddeley** [comment]
Should now be fixed
