### ISSUE TITLE
[BUG] clusterofone h5 spooling issue

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1189]
**Describe the bug**
suspect a 5d datasource change

```
c:\userfiles\code\python-microscopy\PYME\DSView\splashScreen.py:117: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  MemBitmap = wx.EmptyBitmap(s.GetWidth(), s.GetHeight())
ERROR:PYME.IO.DataSources.HDFDataSource:dim info not found as table attribute, trying metadata
Traceback (most recent call last):
  File "c:\userfiles\code\python-microscopy\PYME\IO\DataSources\HDFDataSource.py", line 55, in __init__
    dimorder = self._img_data.attrs.DimOrder
  File "C:\ProgramData\Miniconda3\lib\site-packages\tables\attributeset.py", line 301, in __getattr__
    "'%s'" % (name, self._v__nodepath))
AttributeError: Attribute 'DimOrder' does not exist in node: '/PZFImageData'
```

**To Reproduce**
1. PYMEAcquire
2. spool to cluster
3. check h5 cluster of one
4. acquire
5. open in PYMEImage
6. seeeeee error

**Expected behavior**

**Screenshots**

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: win10
 - Python version: 3.7
 - numpy version: 1.19.2

**Additional context**

**Comment by David-Baddeley** [comment]
The error should be handled, and can be ignored for now. Just a reminder to
fix the spooling so we actually save the info.
