### ISSUE TITLE
[BUG] checksum fit regression

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1202]
**Describe the bug**
localizing from PYMEAcquire simulated h5 file with a cluster of one, ChecksumFR
```
===========================================================================
Error in rule: 000000-aaec8bbfc4e142cc8315c32e695fac12 running task: 130 on WEM24C:69744

taskDescr:
----------
{'id': '000000-aaec8bbfc4e142cc8315c32e695fac12~130', 'type': 'localization', 'taskdef': {'frameIndex': '130', 'metadata': 'PYME-CLUSTER://WEM24C/aesb/2021_8_9/analysis/9_8_series_A_checksum0.h5r.json'}, 'inputs': {'frames': 'C:\\Users\\aesb\\PYMEData\\aesb\\2021_8_9\\9_8_series_A.h5'}, 'outputs': {'fitResults': 'http://127.0.0.1:64832/__aggregate_h5r/aesb/2021_8_9/analysis/9_8_series_A_checksum0.h5r/FitResults', 'driftResults': 'http://127.0.0.1:64832/__aggregate_h5r/aesb/2021_8_9/analysis/9_8_series_A_checksum0.h5r/DriftResults'}}

Traceback:
----------
Traceback (most recent call last):
  File "c:\userfiles\andrew\code\python-microscopy\PYME\cluster\taskWorkerHTTP.py", line 309, in computeLoop
    res = task()
  File "c:\userfiles\andrew\code\python-microscopy\PYME\localization\remFitBuf.py", line 545, in __call__
    self.res[i] = fitFac.FromPoint(p.x, p.y)
  File "c:\userfiles\andrew\code\python-microscopy\PYME\localization\FitFactories\ChecksumFR.py", line 58, in FromPoint
    ch_sigma = zlib.crc32(sigma.data)
BufferError: memoryview: underlying buffer is not C-contiguous
```

for reference:
```
>>> image.dataSource.h5File.root.ImageData
/ImageData (EArray(535, 256, 256), shuffle, zlib(2)) ''
  atom := UInt16Atom(shape=(), dflt=0)
  maindim := 0
  flavor := 'numpy'
  byteorder := 'little'
  chunkshape := (2, 256, 256)
```

**To Reproduce**
1. PYMEAcquire
2. simulate some points, save to h5 
3. PYMEImage open the h5
4. PYMEClusterOfOne
5. localize with checksumFR and Background -30:0, using 25th percentile in fit
6. see error

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: Win10
 - Python version: 3.7
 - numpy version: 1.19
 - wxpython version [if a UI bug]: 4.0.4

**Comment by David-Baddeley** [comment]
Suspect this is numpy version related, in any case should be fixable with a
ravel() call or similar.
