### ISSUE TITLE
[BUG] httpspooler_v2.finished fails, spooler missing stopping flag

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1230]
**Describe the bug**
```
Traceback (most recent call last):
  File "C:\Users\aesb\Miniconda3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\aesb\Miniconda3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\userfiles\andrew\code\python-microscopy\PYME\cluster\rules.py", line 248, in push
    post_args = self.prepare()
  File "c:\userfiles\andrew\code\python-microscopy\PYME\cluster\rules.py", line 576, in prepare
    if self.data_complete:
  File "c:\userfiles\andrew\code\python-microscopy\PYME\cluster\rules.py", line 664, in data_complete
    return self.spooler.finished()
  File "c:\userfiles\andrew\code\python-microscopy\PYME\IO\HTTPSpooler_v2.py", line 98, in finished
    return self._stopping
AttributeError: 'Spooler' object has no attribute '_stopping'
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10]
 - Python version:
 - numpy version:
 - wxpython version [if a UI bug]:

**Additional context**

**Comment by barentine** [comment]
fixed with merge of #1222
