### ISSUE TITLE
tif PSF crashes PRI analysis - needs patch for several ofind_XX modules

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#13]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/13) by Christian Soeller (Bitbucket: [christian_soeller](https://bitbucket.org/christian_soeller), ).**

----------------------------------------

Hi David,

With other PSF formats allowed, ofind_pri.py and a few related ones with a ``preparePSF`` method need updating, roughly as suggested below. With that fix everything tested fine with a OME TIFF psf.

Cheers,
Christian

```
#!patch

@@ -107,6 +107,7 @@
 
 def preparePSF(md, axis):
     global PSFFileName, lobeSeparation
+    from PYME.IO.image import ImageStack
     
     PSFFilename = md.PSFFile
                 
@@ -115,10 +116,10 @@
         try:
             ps, vox = md.taskQueue.getQueueData(md.dataSourceID, 'PSF')
         except:
-            fid = open(getFullExistingFilename(PSFFilename), 'rb')
-            ps, vox = pickle.load(fid)
-            fid.close()
-            
+            iStack = ImageStack(filename=PSFFilename)
+            ps = iStack.data[:,:,:].squeeze()
+            vox = iStack.mdh.voxelsize
+
         ps = ps.max(2)
         ps = ps - ps.min()
         ps = ps /ps.max()

```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Thanks! I'd forgotten about the PSF usage in the various ofinds. 

I'm beginning to think that we should possibly add a few sanity checks at the same time - when restricted to .psf we knew that we had extracted the PSFs and that they would have a suitable size (unless specifically altered) and data type. By allowing .tif we open up the possibility that people will use some malformed PSF that they have got form ImageJ or similar. Maybe your idea of saving as TIFF with a custom extension wasn't so bad (although I don't really like to do that on principle). I wonder if we should write something into the metadata on saving and raise an error / warning if that is not present.

**Comment by David-Baddeley** [comment]
**Original comment by Christian Soeller (Bitbucket: [christian_soeller](https://bitbucket.org/christian_soeller), ).**

----------------------------------------

Yes, I agree that just allowing TIFF could get us into trouble. The psf2 extension was aiming that way but I also see the ugliness in that. The presence of a metadata tag could fill in for that and be automatically written by the extract-PSF module. What would happen anyway if a TIFF without metadata is presented - as we are in on-GUI mode it should also result in a comprehensible error.

**Comment by David-Baddeley** [comment]
**Original comment by Christian Soeller (Bitbucket: [christian_soeller](https://bitbucket.org/christian_soeller), ).**

----------------------------------------

PS If the metadata tag is present dh5view could also open a tiff psf in the psf viewer mode - as is now done with *.psf files?

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Resolved with latest push.

Recognition of .tif PSFs in viewer punted to a new enhancement issue:
https://bitbucket.org/david_baddeley/python-microscopy/issues/14/add-metadata-to-psf-saved-as-tif-to

**Comment by David-Baddeley** [comment]
**Original comment by Christian Soeller (Bitbucket: [christian_soeller](https://bitbucket.org/christian_soeller), ).**

----------------------------------------

Small fly in the ointment - TIF loads as float32 - and np.float appears to be float64 on current architectures:


```
#!python

>>> ps = image.data[:,:,:].squeeze()
>>> ps.dtype
dtype('float32')
>>> ps.dtype.type
<type 'numpy.float32'>
>>> ssubclass(ps.dtype.type, np.float)
False
>>> issubclass(ps.dtype.type, np.float32)
True
```

Net result is that psfExtract written TIF psfs bomb on load with a RunTimeError with the check in ``load_psf``.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Should be fixed with a change to `np.floating` rather than `np.float`. (I thought I had tried both and both worked ...)

**Comment by David-Baddeley** [comment]
**Original comment by Christian Soeller (Bitbucket: [christian_soeller](https://bitbucket.org/christian_soeller), ).**

----------------------------------------

Yes, that does it and fixes the loading.

I have come across one showstopper though that I do not comprehend right now. With the load_psf approach I now consistently trip up the error in priEstimator.py that I had reported earlier, however, now with PSFs that worked perfectly fine before. I tried reverting to the pre-commit stage and there everything works fine again.

This probably provides a clue what this error really originates from but I have not yet been able to investigate. Will do as I find time.


```
#!python

Traceback (most recent call last):
  File "/Users/csoe002/Documents/src/python-microscopy-exeter/PYME/DSView/modules/LMAnalysis.py", line 260, in <lambda>
    bTestF.Bind(wx.EVT_BUTTON, lambda e : self.lmanal.OnTestFrame(e))
  File "/Users/csoe002/Documents/src/python-microscopy-exeter/PYME/DSView/modules/LMAnalysis.py", line 589, in OnTestFrame
    ft, fr = self.testFrame()
  File "/Users/csoe002/Documents/src/python-microscopy-exeter/PYME/DSView/modules/LMAnalysis.py", line 802, in testFrame
    res = ft(gui=gui,taskQueue=self.tq)
  File "/Users/csoe002/Documents/src/python-microscopy-exeter/PYME/localization/remFitBuf.py", line 533, in __call__
    fitFac = fitMod.FitFactory(self.data, md, background = self.bg, noiseSigma = self.sigma)
  File "/Users/csoe002/Documents/src/python-microscopy-exeter/PYME/localization/FitFactories/InterpFitR.py", line 126, in __init__
    self.startPosEstimator.calibrate(self.interpolator, metadata)
  File "/Users/csoe002/Documents/src/python-microscopy-exeter/PYME/localization/FitFactories/zEstimators/priEstimator.py", line 129, in calibrate
    sp, u = splprep([zm], u=dwm, s=1)
  File "/Users/csoe002/anaconda/lib/python2.7/site-packages/scipy/interpolate/fitpack.py", line 239, in splprep
    _parcur_cache['ub'] = u[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Could you try running `nosetests` somewhere in the PYME directory - I think there is a PRI test in there somewhere, and it would be interested to see if it passes.

**Comment by David-Baddeley** [comment]
**Original comment by Christian Soeller (Bitbucket: [christian_soeller](https://bitbucket.org/christian_soeller), ).**

----------------------------------------

Ok, will do.
