### ISSUE TITLE
[PROPOSAL] use absolute imports in PYME scripts (e.g. dsviewer.py)

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1346]
**Is your feature request related to a problem? Please describe.**
It can be quite nice to use an interactive debugger sometimes, e.g. the one included with vscode. Unfortunately, relative imports don't always mix well with the command line. As things stand, if I try a debug process I want to attach to, I get the following:
```
(pyme38) andy@Andrews-MacBook-Pro python-microscopy % /Users/andy/miniconda3/envs/pyme38/python.app/Contents/MacOS/python -m debugpy --listen 0.0.0.0:5678 /Users/andy/code/python-microscopy/PYME/DSView/dsviewer.py
Traceback (most recent call last):
  File "/Users/andy/miniconda3/envs/pyme38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/andy/miniconda3/envs/pyme38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/andy/miniconda3/envs/pyme38/lib/python3.8/site-packages/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/Users/andy/miniconda3/envs/pyme38/lib/python3.8/site-packages/debugpy/server/cli.py", line 444, in main
    run()
  File "/Users/andy/miniconda3/envs/pyme38/lib/python3.8/site-packages/debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/Users/andy/miniconda3/envs/pyme38/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Users/andy/miniconda3/envs/pyme38/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/andy/miniconda3/envs/pyme38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/andy/code/python-microscopy/PYME/DSView/dsviewer.py", line 39, in <module>
    from . import modules
ImportError: attempted relative import with no known parent package
```

This can of course be fixed easily by changing the import to 
`from PYME.DSView import modules`

Absolute imports are recommended by pep8, though relative are an 'acceptable alternative' unless you're dealing with 'standard library code' in which case everything should be absolute. I'm happy to [let others argue](https://mail.python.org/pipermail/python-3000/2007-April/006793.html) about why this should/shouldn't matter, I would just like to make debugging as easy as possible for myself and keep the entry barrier low for others too.

**Describe the solution you'd like to implement**
change relative imports in PYME scripts to absolute imports

**Describe alternatives you've considered**
manually editing the scripts every time I want to debug something involving the PYME GUI interactively

**Additional context**

**What potential side effects do the proposed changes have?**
- Is it new functionality, or a change to existing functionality?
ability to debug PYMEImage etc. interactively
- Will it change how users interact with the software?
only if they're trying to debug it interactively 
- Will it change the dependency landscape?
no

**Comment by barentine** [comment]
complete with merge of #1347 - thanks David!
