### ISSUE TITLE
[BUG] Recipe run failure kills pipeline, forces restart

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#1353]
**Describe the bug**
If recipe runs fail in a specific way, we get the following Traceback.

```
Traceback (most recent call last):
  File "/Users/zachmarin/opt/miniconda3/envs/pyme/lib/python3.8/site-packages/wx/core.py", line 2326, in Notify
    self.notify()
  File "/Users/zachmarin/opt/miniconda3/envs/pyme/lib/python3.8/site-packages/wx/core.py", line 3532, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/Users/zachmarin/Code/python-microscopy/PYME/recipes/recipeGui.py", line 559, in update
    self.recipePlot.draw()
  File "/Users/zachmarin/Code/python-microscopy/PYME/recipes/recipeGui.py", line 104, in draw
    node_positions, connecting_lines = recipeLayout.layout(dg)
  File "/Users/zachmarin/Code/python-microscopy/PYME/recipes/recipeLayout.py", line 37, in layout
    ips, yvs = depGraph.arrangeNodes(dg)
  File "/Users/zachmarin/Code/python-microscopy/PYME/misc/depGraph.py", line 123, in arrangeNodes
    fd_ws += [1.0/(1 + ips[rr][0] - xc) for rr in gnodes if rr in ips.keys()]
  File "/Users/zachmarin/Code/python-microscopy/PYME/misc/depGraph.py", line 123, in <listcomp>
    fd_ws += [1.0/(1 + ips[rr][0] - xc) for rr in gnodes if rr in ips.keys()]
ZeroDivisionError: float division by zero
```

While the pipeline remains editable, it will no longer run if values are changed. The program must be restarted.

**To Reproduce**

Run "Shrinkwrap membrane surface" with a non-existent data source as an input to "points".

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: OSX Venture 13.13.1
 - Python version: 3.8.13
 - numpy version: 1.23.1
 - wxpython version [if a UI bug]: 4.1.1

**Comment by David-Baddeley** [comment]
Hmm, I can't seem reproduce that exact error. Could you provide the recipe text? For me I can get to a point where the pipeline is not editable, but it's resolvable by editing the text version and clicking 'Apply text changes' (i.e. I don't need to restart).
