### ISSUE TITLE
[Proposal] propagate or log recipe errors in PYMEImage

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#1363]
**Describe the bug**
Appreciate that it's now easy to localize where a recipe has failed, and in general we've made some nice usability improvements there/in PYMEVis. It's been awhile since I've debugged a recipe in PYMEImage, which used to be a pretty handy sandbox. Now I get a traceback which only tells me what module failed. Would be great if we could propagate up errors further here so I can debug non-interactively / folks can easily share errors with us.

<details> <summary> Traceback </summary>

```
DEBUG:PYME.recipes.recipe:recipe.execute()
DEBUG:PYME.recipes.recipe:Executing <PYME.recipes.filters.GaussianFilter object at 0x16a971ea0>
/Users/andy/code/python-microscopy/PYME/IO/MetaDataHandler.py:666: UserWarning: DictMDHandler is not yet fully supported, and will likely cause failures for anything related to localisation fitting
  warnings.warn('DictMDHandler is not yet fully supported, and will likely cause failures for anything related to localisation fitting')
DEBUG:PYME.recipes.recipe:Executing <PYME.recipes.base.ExtractChannel object at 0x16a6aa6d0>
/Users/andy/code/python-microscopy/PYME/recipes/base.py:947: PYMEDeprecationWarning: This will either disappear or change function as we move to a 5D data model. Use the explicit .data_xytc instead, or even better, change to using the 5D model as image.data_xyztc or image.voxels
  chan = image.data[:,:,:,self.channelToExtract]
DEBUG:PYME.recipes.recipe:Executing <PYME.recipes.base.ExtractChannel object at 0x16a60f0e0>
DEBUG:PYME.recipes.recipe:Executing <PYME.recipes.processing.Threshold object at 0x169b39220>
DEBUG:PYME.recipes.recipe:Executing <PYME.recipes.base.ExtractChannel object at 0x16a971900>
DEBUG:PYME.recipes.recipe:Executing <PYME.recipes.base.ExtractChannel object at 0x16a9718b0>
DEBUG:PYME.recipes.recipe:Executing <PYME.recipes.processing.ColocalisationEDT object at 0x16a971f40>
/Users/andy/code/python-microscopy/PYME/recipes/processing.py:2162: PYMEDeprecationWarning: This will either disappear or change function as we move to a 5D data model. Use the explicit .data_xytc instead, or even better, change to using the 5D model as image.data_xyztc or image.voxels
  imA = inputImage.data[:, :, :, 0].squeeze()
ERROR:PYME.recipes.recipe:Error in recipe module: <PYME.recipes.processing.ColocalisationEDT object at 0x16a971f40>
Traceback (most recent call last):
  File "/Users/andy/code/python-microscopy/PYME/recipes/recipe.py", line 237, in execute
    m.execute(self.namespace)
  File "/Users/andy/code/python-microscopy/PYME/recipes/base.py", line 263, in execute
    out = {v : ret[k] for v, k in self._output_traits.items()}
  File "/Users/andy/code/python-microscopy/PYME/recipes/base.py", line 263, in <dictcomp>
    out = {v : ret[k] for v, k in self._output_traits.items()}
KeyError: 'edt_coloc_0im_1mask'
DEBUG:PYME.recipes.recipe:removing failed module dependencies
DEBUG:PYME.recipes.recipe:notifying failure
Traceback (most recent call last):
  File "/Users/andy/code/python-microscopy/PYME/recipes/recipe.py", line 237, in execute
    m.execute(self.namespace)
  File "/Users/andy/code/python-microscopy/PYME/recipes/base.py", line 263, in execute
    out = {v : ret[k] for v, k in self._output_traits.items()}
  File "/Users/andy/code/python-microscopy/PYME/recipes/base.py", line 263, in <dictcomp>
    out = {v : ret[k] for v, k in self._output_traits.items()}
KeyError: 'edt_coloc_0im_1mask'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/andy/code/python-microscopy/PYME/ui/progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "/Users/andy/code/python-microscopy/PYME/DSView/modules/recipes.py", line 102, in RunCurrentRecipe
    self.outp = self.activeRecipe.execute(input=self.image)
  File "/Users/andy/code/python-microscopy/PYME/recipes/recipe.py", line 282, in execute
    raise RecipeExecutionError('Recipe execution failed in module %s' % self._failing_module._module_name, self ) from e
PYME.recipes.recipe.RecipeExecutionError: Recipe execution failed in module processing.ColocalisationEDT
```

</details>

<details> <summary> recipe </summary> 

```
- processing.Threshold:
    dimensionality: XYZ
    inputName: smoothed
    method: otsu
    outputName: filtered_image
- filters.GaussianFilter:
    dimensionality: XYZ
    inputName: input
    outputName: smoothed
- base.ExtractChannel:
    inputName: filtered_image
    outputName: chan0_mask
- base.ExtractChannel:
    channelToExtract: 1
    inputName: filtered_image
    outputName: chan1_mask
- base.ExtractChannel:
    inputName: input
    outputName: chan0
- base.ExtractChannel:
    channelToExtract: 1
    inputName: input
    outputName: chan1
- processing.ColocalisationEDT:
    inputImage: chan0
    inputImageB: chan1
    inputMask: chan1_mask
    inputRoiMask: chan0_mask
    outputPlot: coloc_plot_0im_1mask
    outputTable: edt_coloc_0im_1mask
- processing.ColocalisationEDT:
    inputImage: chan1
    inputImageB: chan0
    inputMask: chan0_mask
    inputRoiMask: chan1_mask
    outputPlot: coloc_plot_1im_0mask
    outputTable: edt_coloc_1im_0mask

```

</details>

**To Reproduce**
1. PYMEImage a 2 color z stack (saved as h5)
3. load or build recipe 
4. Recipes>run current recipe
5. See errors. 
6. wonder whether we're doing something weird with error reporting in recipe modules

**Expected behavior**

**Screenshots**

<img width="1061" alt="Screen Shot 2023-05-16 at 7 00 03 PM" src="https://github.com/python-microscopy/python-microscopy/assets/31105780/7071350a-3710-4187-a634-2764b26a0331">

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: osx12.6.2
 - Python version: 3.8
 - numpy version: 1.23.5
 - wxpython version [if a UI bug]: 4.2.0

**Comment by barentine** [comment]
Note: looks like error was not in the module after all, but really in the line
`            out = {v : ret[k] for v, k in self._output_traits.items()}`

where `self._output_traits.items()` evaluates to `dict_items([('outputTable', 'edt_coloc_0im_1mask'), ('outputPlot', 'coloc_plot_0im_1mask')])` and ret.keys() yields: `dict_keys(['outputTable', 'outputPlot'])`
and can be keyed into:
'''
ret['outputTable']
<PYME.IO.tabular.MappingFilter object at 0x16b8a1e20>
ret['outputPlot']
<PYME.recipes.graphing.Plot object at 0x1021dd070>
'''


I believe the line should read: `out = {k : ret[v] for v, k in self._output_traits.items()}`

**Comment by barentine** [comment]
ahhh, I see now you already found and fixed this @David-Baddeley. Sorry I was not at the head
