### ISSUE TITLE
render 3D image[SUPPORT]

### ISSUE THREAD

**Issue by Z-Qing** [python-microscopy/python-microscopy#1379]
Hi, all. I just installed pyme using .exe file on win11 system. I used the Genterate|3D Gaussian tab in PYME Visualize GUI and got the image in pop-up window successfully. Then I trid to use 3D|3D Volume, which didn't work. Here is the error message:

 Error whilst running &3D>3D Volume
==============================================
python-microscopy=23.05.17.post2[conda]
python=3.7.16, platform=win32
numpy=1.21.5, wx=4.0.4 msw (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "D:\pyme\lib\site-packages\PYME\DSView\modules\vis3D.py", line 247, in On3DVolume
    from enthought.mayavi import mlab
ModuleNotFoundError: No module named 'enthought'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\pyme\lib\site-packages\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "D:\pyme\lib\site-packages\PYME\DSView\modules\vis3D.py", line 249, in On3DVolume
    from mayavi import mlab
ModuleNotFoundError: No module named 'mayavi'

Thanks for your help.

ps, I also noticed that after I closed the result of 3d Gaussian. The ram wasn't released.

**Comment by David-Baddeley** [comment]
Hi Qing,

volume rendering requires mayavi to be installed alongside PYME. We don't do this by default as it can be really tricky to get mayavi installed, and this is the only place it's used. We should, however, make the error messages here a bit more informative, and tell you that you need to install it separately. For a long time there were not any conda packages for mayavi available for python 3, so to get mayavi you pretty much needed to build it from source. It now seems that there are packages available for python >= 3.8, so when we get the installer working with py3.8 (hopefully within the next month) it should get easier to also install mayavi.

I'll look into the memory usage.

David

**Comment by Z-Qing** [comment]
Hi David. Thanks for your timely reply. 
I installed pyme and mayavi with python 3.8. The 3d volume works now.
However, the 3d isosurface (coloured) doesn't. Here is the error message.

 Error whilst running &3D>3D Isosurface (coloured)
==============================================
python-microscopy=23.05.17.post2[unknown]
python=3.8.16, platform=win32
numpy=1.23.1, wx=4.2.1 msw (phoenix) wxWidgets 3.2.2.1

Traceback
=========
Traceback (most recent call last):
  File "D:\anaconda3\envs\pyme\lib\site-packages\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "D:\anaconda3\envs\pyme\lib\site-packages\PYME\DSView\modules\vis3D.py", line 208, in isosurf_coloured
    assert(self.image.data_xyztc.shape[4] ==2)
AssertionError

Thanks for your help.
