### ISSUE TITLE
[BUG] Skeletonize mesh does not work in PYMEVisualize 23.05.17.post2[conda]

### ISSUE THREAD

**Issue by ppa007hot** [python-microscopy/python-microscopy#1399]
**Describe the bug**
Skeletonize mesh does not work.

**To Reproduce**
1. Go to 'Mesh'
2. Click on 'Skeletonize mesh'
3. See error

**Screenshots**
 Error whilst running Mesh>Skeletonize mesh
==============================================
python-microscopy=23.05.17.post2[conda]
python=3.7.16, platform=win32
numpy=1.21.5, wx=4.0.4 msw (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "C:\Users\ms3832\AppData\Local\python-microscopy\lib\site-packages\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "C:\Users\ms3832\AppData\Local\python-microscopy\lib\site-packages\ch_shrinkwrap\visgui_modules\surface_feature_extraction.py", line 24, in <lambda>
    visFr.AddMenuItem('Mesh', 'Skeletonize mesh', lambda e: skeletonize(visFr))
  File "C:\Users\ms3832\AppData\Local\python-microscopy\lib\site-packages\ch_shrinkwrap\visgui_modules\surface_feature_extraction.py", line 11, in skeletonize
    sw = SkeletonizeMembrane(recipe, invalidate_parent=False, input=surf_name, output=skeleton_name, points='filtered_localizations')
  File "C:\Users\ms3832\AppData\Local\python-microscopy\lib\site-packages\PYME\recipes\base.py", line 166, in __init__
    self.trait_set(trait_change_notify=False, **kwargs) #don't notify here - next set will do notification.
  File "C:\Users\ms3832\AppData\Local\python-microscopy\lib\site-packages\traits\has_traits.py", line 1429, in trait_set
    setattr(self, name, value)
traits.trait_errors.TraitError: Cannot set the undefined 'points' attribute of a 'SkeletonizeMembrane' object.

**Comment by David-Baddeley** [comment]
This is due to an error in ch-shrinkwrap, transferring there ...
