### ISSUE TITLE
potential bug: *.psf pickles for localisation noetests not recognised as pickles on OS X

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#16]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/16) by Christian Soeller (Bitbucket: [christian_soeller](https://bitbucket.org/christian_soeller), ).**

----------------------------------------

# Affects: *.psf files in PYME/localisation/Tests #

These all raise ``IOError: Failed to interpret file 'PYME/localization/Test/astig_theory.psf' as a pickle`` on my macbook, e.g.

```
#!python

======================================================================
ERROR: Test the 3D interpolated fit by fitting some randomly generated events. The pass condition here is fairly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/csoe002/anaconda/envs/pyme-test/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/localization/Test/test_localization_algorithms.py", line 77, in test_SplitterFitInterpNR_astigmatism
    tj.runTests(nTests=100)
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/localization/Test/fitTestJigWC.py", line 98, in runTests
    self.data, self.x0, self.y0, self.z0 = self.simMod.FitFactory.evalModel(p, md2, roiHalfSize=rs)#, roiHalfSize= roiHalfWidth))
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/localization/FitFactories/SplitterFitInterpNR.py", line 184, in evalModel
    return cls._evalModel(params, md, xs, ys, x, y)
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/localization/FitFactories/SplitterFitInterpNR.py", line 200, in _evalModel
    if interpolator.setModelFromFile(md.PSFFile, md):
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/localization/FitFactories/Interpolators/baseInterpolator.py", line 100, in setModelFromFile
    mod, voxelsize_nm = load_psf(modName)
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/IO/load_psf.py", line 15, in load_psf
    img = ImageStack(filename=filename)
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/IO/image.py", line 221, in __init__
    self.Load(filename)
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/IO/image.py", line 928, in Load
    self._loadPSF(filename)
  File "/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/IO/image.py", line 523, in _loadPSF
    self.data, vox = numpy.load(fn)
  File "/Users/csoe002/anaconda/envs/pyme-test/lib/python2.7/site-packages/numpy/lib/npyio.py", line 352, in load
    "Failed to interpret file %s as a pickle" % repr(file))
IOError: Failed to interpret file '/Users/csoe002/Documents/src/python-microscopy-christians-scmos-changes/PYME/localization/Test/astig_theory.psf' as a pickle


```

It is either something specific on my mac or a PC/mac/numpy version incompatibility for the pickles in question. If confirmed may be useful to move to TIFF with ``ImageType`` MD set properly.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Hmm, they work fine for me (OSX). Can you read them with cPickle.load?

**Comment by David-Baddeley** [comment]
**Original comment by Christian Soeller (Bitbucket: [christian_soeller](https://bitbucket.org/christian_soeller), ).**

----------------------------------------

I now realise that this likely reflects the MetaDataHandler module move because I get:


```
#!python

In [1]: fi = open('PYME/localization/Test/test.psf','rb')

In [2]: import cPickle

In [3]: ret = cPickle.load(fi)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-1b6d51ec37ef> in <module>()
----> 1 ret = cPickle.load(fi)

ImportError: No module named MetaDataHandler

```
The load fine on systems that still have a pyc of the old module. I have deliberately deleted all these to avoid confusion. I converted with a little shell script:


```
#!python

import sys
import argparse

def main():
    # options parsing
    op = argparse.ArgumentParser(description='convert old style PSFs to new style.')
    op.add_argument('psfname', metavar='psfname', default=None,
                    help='filename of old style PSF')
    op.add_argument('outname', metavar='outname', default=None,
                    help='filename for converted PSF')
    op.add_argument('-d', '--debug', action='store_true')
    
    args = op.parse_args()

    try:
        import cPickle as pickle
    except ImportError:
        import pickle

    # we need to trick pickle into thinking that
    #    PYME.Acquire.MetaDataHandler is still available
    import PYME.IO.MetaDataHandler as MD
    sys.modules['PYME.Acquire.MetaDataHandler'] = MD
    with open(args.psfname,'rb') as inpfi:
        psf = pickle.load(inpfi)

    if args.debug:
        print "psf: %s, %s" % (repr(psf[0].shape), repr(psf[0].dtype))
        print psf[1]

    del sys.modules['PYME.Acquire.MetaDataHandler']
    with open(args.outname,'wb') as outfi:
        pickle.dump(psf,outfi)

if __name__ == "__main__":
    main()
```

Perhaps we can convert the files in the repo?

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

.psfs used for testing converted to .tif
