### ISSUE TITLE
Color-assignment error in Python 3

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/python-microscopy#165]
I tried to assign color channels for salvaged fluorescence in the Colour tab in VisGUI and received the following traceback.

```
Traceback (most recent call last):                                                                                        

File "c:\users\laf62\python-microscopy\PYME\LMVis\colourPanel.py", line 298, in OnSpecAdd                                 self.pipeline.colour_mapper.species_ratios[key] = float(val)                                                          

File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\traits\trait_handlers.py", line 3318, in __setitem__              raise excp                                                                                                            

File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\traits\trait_handlers.py", line 3314, in __setitem__              key = validate(object, self.name, key)                                                                                

File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\traits\trait_handlers.py", line 1190, in validate                 self.error(object, name, value)                                                                                       

File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\traits\trait_handlers.py", line 236, in error                     object, name, self.full_info(object, name, value), value                                                            

traits.trait_errors.TraitError: Each key of the 'species_ratios' trait of a ProcessColour instance must be a value of class 'str', but a value of b'A' <class 'bytes'> was specified. 
```

**Comment by David-Baddeley** [comment]
fixed in #166
