### ISSUE TITLE
Can't analyze TIFF stack w/o metadata

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#30]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/30) by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

AttributeError: NestedClassMDHandler instance has no attribute 'EstimatedLaserOnFrameNo'
Traceback (most recent call last):
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\ParallelTasks\taskWorkerZC.py", line 91, in main
    tasks = tq.getTasks(procName, PYME.version.version)
  File "C:\ProgramData\Anaconda2\lib\site-packages\Pyro\core.py", line 381, in __call__
    return self.__send(self.__name, args, kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\Pyro\core.py", line 456, in _invokePYRO
    return self.adapter.remoteInvocation(name, Pyro.constants.RIF_VarargsAndKeywords, vargs, kargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\Pyro\protocol.py", line 497, in remoteInvocation
    return self._remoteInvocation(method, flags, *args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\Pyro\protocol.py", line 572, in _remoteInvocation
    answer.raiseEx()
  File "C:\ProgramData\Anaconda2\lib\site-packages\Pyro\errors.py", line 72, in raiseEx
    raise self.excObj
AttributeError: NestedClassMDHandler instance has no attribute 'EstimatedLaserOnFrameNo'

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

fix
![bugfix.png](https://bitbucket.org/repo/kAoqj6/images/1471844056-bugfix.png)

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

Might be a different bug, but if you try to open a .h5r file that was analyzed w/o metadata you get:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\VisGUI-script.py", line 11, in <module>
    load_entry_point('PYME', 'console_scripts', 'VisGUI')()
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\LMVis\VisGUI.py", line 405, in main
    main_(args.file, use_shaders=args.use_shaders, args=args)
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\LMVis\VisGUI.py", line 379, in main_
    application = VisGuiApp(filename, use_shaders, args, 0)
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\LMVis\VisGUI.py", line 365, in __init__
    wx.App.__init__(self, *args)
  File "C:\ProgramData\Anaconda2\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8631, in __init__
    self._BootstrapApp()
  File "C:\ProgramData\Anaconda2\lib\site-packages\wx-3.0-msw\wx\_core.py", line 8196, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\LMVis\VisGUI.py", line 370, in OnInit
    self.main = VisGUIFrame(None, self.filename, use_shaders=self.use_shaders, cmd_args=self.cmd_args)
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\LMVis\VisGUI.py", line 165, in __init__
    self.OpenFile(filename)
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\LMVis\visCore.py", line 607, in OpenFile
    self.pipeline.OpenFile(filename, **args)
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\LMVis\pipeline.py", line 600, in OpenFile
    ds = self._ds_from_file(filename, **kwargs)
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\LMVis\pipeline.py", line 513, in _ds_from_file
    ds = tabular.h5rDSource(filename)
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\IO\tabular.py", line 267, in __init__
    h5rSource.__init__(self, h5fFile, 'DriftResults')
  File "c:\users\zrc4\pycharmprojects\python-microscopy-michael-clustering\PYME\IO\tabular.py", line 208, in __init__
    raise RuntimeError('Was expecting to find a "%s" table' % tablename)
RuntimeError: Was expecting to find a "DriftResults" table

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

That is because that file wasn't analyzed, and no fitResults entry was found

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

@david_baddeley , I can't close this, but this issue has been resolved with a recent PR that was merged.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Marking as resolved (as noted by Andrew)
