### ISSUE TITLE
Cleaner/explained tif/tiff handling would be nice

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#32]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/32) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

The parts that I find confusing:

*  Bioformats is not a required package, nor is it listed at all in the 'prerequisites for the adventurous' part of the docs (though it is included in the development install instructions), yet we default to it for .tiffs.

* I'm not very familiar with bioformats - is there a reason one would care whether their .tiff was loaded via bioformats rather than native support?

* Java gets upset at me if I open more than one tiff (even if I delete the reference to the first before), saying that it could not create a java VM, which does not get fixed by making the heap larger (I tried 10 GB).

* Most viewers aren't able to load the PYME-saved tiffs or tifs

* Saving a .tif requires metadata, but saving .tiff does not:

```
#!Traceback

image.Save('/home/aeb85/Desktop/test_tif2.tiff')
((0, 256, 1), '(I0\nI256\nI1\ntp1\n.')
((0, 256, 1), '(I0\nI256\nI1\ntp1\n.')
((0, 189, 1), '(I0\nI189\nI1\ntp1\n.')
(0, 256, 1)
from PYME.IO.image import ImageStack
a = ImageStack(data=image.data)
a
<PYME.IO.image.ImageStack object at 0x7f361e749e10>
a.Save('/home/aeb85/Desktop/test_tiff3.tif')
((0, 256, 1), '(I0\nI256\nI1\ntp1\n.')
((0, 256, 1), '(I0\nI256\nI1\ntp1\n.')
((0, 189, 1), '(I0\nI189\nI1\ntp1\n.')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/image.py", line 999, in Save
    self.filename = dataExporter.ExportData(self.data, self.mdh, self.events, filename=filename, progressCallback=progressCallback)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/dataExporter.py", line 560, in ExportData
    exp.Export(ds, filename, slice(0, ds.shape[0], 1), slice(0, ds.shape[1], 1), slice(0, ds.shape[2], 1),mdh, events, origName, progressCallback=progressCallback)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/dataExporter.py", line 231, in Export
    description=xmd.getXML(dw)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/MetaDataHandler.py", line 695, in getXML
    self.pixels.setAttribute('PhysicalSizeX', '%3.4f' % self.getEntry('voxelsize.x'))
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/MetaDataHandler.py", line 544, in getEntry
    raise RuntimeError('Requested node not found')
RuntimeError: Requested node not found
```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Thanks! I'll write a bit of documentation about how TIFFs are handled, which hopefully makes things a bit clearer. We should probably also flag the .tiff saving as a bug (in theory it shouldn't be possible).

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

As a comment on bioformats specifically: 

* it's neat because it can load pretty much anything
* it's a pain in the arse to install (so I'm reluctant to add it to the dependencies on windows or linux - at least until I've built conda packages for it like I did for OSX)
* it can be a bit flaky

The reason for the current setup is that:

* we can load 90% of tiffs natively (i.e. through the tifffile module)
* there are roughly 10% of tiffs which we can't load natively. There needs to be a way of loading these using bioformats instead. Adding an extra 'f' to the extension to flag these as odd tiffs is a pretty ugly solution, but it's the best I've come up with so far.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

See new TIFF documentation at http://python-microscopy.org/doc/tiff_handling.html

I've also added a warning when saving as `.tiff`.

I'll leave this issue open for now.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Hi @david_baddeley , I think we can resolve this issue, though it would be worth recompiling the docs, as the tiff_handling.rst contains information on how to export images for use in publications, but the online version still reads:

"There was historically a menu item to do this, which allowed you to export as .png or a variety of other bitmap forms, but that seems to have vanished [FIXME]. The functionality is still present, however, for copying and pasting"

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Also, thank you for adding all of the clarifications @david_baddeley !

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

resolved with added documentation
