### ISSUE TITLE
signal has no SIGHUP on windows -> can't run distributor from windows machine

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#33]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/33) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

As documented [here:](https://docs.python.org/2/library/signal.html#signal.signal)

```
#!python

Traceback (most recent call last):
  File "C:\Users\Bergamot\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\Bergamot\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\bergamot\pycharmprojects\python-microscopy\PYME\ParallelTasks\distributor.py", line 437, in <module>
    signal.signal(signal.SIGHUP, on_SIGHUP)
AttributeError: 'module' object has no attribute 'SIGHUP'
```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Is there a good reason for wanting to run the distributor on Windows? I'd never really taken anything other than *nix into account when writing the distributor and would certainly not want to run it or the data servers on windows in production. There might, however be a case for having it run on windows for testing and development.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Windows workaround added in commit c5f72f0. Use on windows is still not recommended.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

You guessed my reason exactly - I was interested in running the distributor on a computer with higher bandwidth connection to the switch. Thanks!

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

That's not really the type of testing I was thinking of (I was more thinking of a low-speed 'cluster of one' type scenario where you run everything on your laptop). There are 2 major issues in what you propose. Firstly, the distributor is unlikely to perform well on Windows, but more importantly there are much large issues if the distributor needs more bandwidth to do it's job (namely that it will bring spooling to a grinding halt).

The issues:

*  spooling needs roughly 80% of the total cluster bandwidth (potentially a little less if compression is working well, but not much less)

* any overhead related to getting directory listings, task distribution, filing of analysis results etc ... needs to fit into the remaining 20%. Of these tasks, filing results probably has the most legitimate bandwidth demand. If the distributor is taking more than ~4-5% of the total bandwidth we have an issue. If the distributor is taking more than 10% (the bandwidth of a single compute node), we have a big issue. This means that shifting it to a higher bandwidth node is likely to create more problems than it solves.

* I had thought I'd solved the distributor bandwidth issues by compressing the messages prior to sending. In my memory this got us down to around 30MB/s under a stress test. Have you verified that compression is being used for distributor traffic? Are you using the Python versions of both distributor and nodeserver?

* If we haven't solved the distributor bandwidth problem, we're going to need to completely rethink distribution and go back to something like my original brief rather than than the architecture that Leo eventually settled on.
