### ISSUE TITLE
[BUG] Byte ordering in MATLAB source files causes saving issue in `tabular.TabularBase.to_hdf`

### ISSUE THREAD

**Issue by zacsimile** [python-microscopy/python-microscopy#330]
**Describe the bug**
If we try to save filtered localizations from a loaded `.mat` file in PYME, we get the following traceback.

<details>
<summary>Traceback</summary>
<pre>
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:180: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(UI_MAXSIZE, key)
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:181: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % minVal)
/Users/zachcm/Code/python-microscopy/PYME/LMVis/filterPane.py:182: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % maxVal)
lw update
hl update
DEBUG:root:pytables open call: /Users/zachcm/Documents/Papers/PYMEVisualize/Data/croppeddata.hdf
DEBUG:root:pytables file open: /Users/zachcm/Documents/Papers/PYMEVisualize/Data/croppeddata.hdf
Traceback (most recent call last):
  File "/Users/zachcm/Code/python-microscopy/PYME/IO/h5rFile.py", line 118, in _appendToTable
    table = getattr(self._h5file.root, tablename)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/group.py", line 836, in __getattr__
    return self._f_get_child(name)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/group.py", line 708, in _f_get_child
    self._g_check_has_child(childname)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``Localizations``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zachcm/Code/python-microscopy/PYME/IO/h5rFile.py", line 210, in _pollQueues
    self._appendToTable(tablename, waiting.popleft())
  File "/Users/zachcm/Code/python-microscopy/PYME/IO/h5rFile.py", line 128, in _appendToTable
    expectedrows=500000)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/file.py", line 1057, in create_table
    track_times=track_times)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/table.py", line 811, in __init__
    descr_from_dtype(nparray.dtype, ptparams=parentnode._v_file.params)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/description.py", line 848, in descr_from_dtype
    "structured arrays with mixed byteorders "
NotImplementedError: structured arrays with mixed byteorders are not supported yet, sorry
ERROR:root:Traceback (most recent call last):
  File "/Users/zachcm/Code/python-microscopy/PYME/IO/h5rFile.py", line 118, in _appendToTable
    table = getattr(self._h5file.root, tablename)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/group.py", line 836, in __getattr__
    return self._f_get_child(name)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/group.py", line 708, in _f_get_child
    self._g_check_has_child(childname)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/group.py", line 395, in _g_check_has_child
    % (self._v_pathname, name))
tables.exceptions.NoSuchNodeError: group ``/`` does not have a child named ``Localizations``

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zachcm/Code/python-microscopy/PYME/IO/h5rFile.py", line 210, in _pollQueues
    self._appendToTable(tablename, waiting.popleft())
  File "/Users/zachcm/Code/python-microscopy/PYME/IO/h5rFile.py", line 128, in _appendToTable
    expectedrows=500000)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/file.py", line 1057, in create_table
    track_times=track_times)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/table.py", line 811, in __init__
    descr_from_dtype(nparray.dtype, ptparams=parentnode._v_file.params)
  File "/Users/zachcm/miniconda3/envs/pyme/lib/python3.6/site-packages/tables/description.py", line 848, in descr_from_dtype
    "structured arrays with mixed byteorders "
NotImplementedError: structured arrays with mixed byteorders are not supported yet, sorry
</pre>
</details>

Further probing suggests this is due to `scipy.io.loadmat` inferring `.mat` file byte order and loading `.mat` column data, in my case, as `little-endian`. The `focus` column, which is loaded into the pipeline by default in PYME, has native byte order. When the MATLAB columns + the `focus` column are converted `to_recarray` in the `to_hdf` function in `tabular.TabularBase`, `tables` throws an error saying we can't combine byte orders in a single structured array.

**To Reproduce**
1. Open any `.mat` file that will be loaded by a `MatfileColumnSource`.
2. Go to `File > Save filtered localizations` and take a look at the traceback. The context manager doesn't catch this particular error, so you'll have to go to the terminal to see it after the context manager says `File>Save filtered localizations ... [COMPLETE]`.

**Expected behavior**
We should be able to save filtered localizations from  a `.mat` file, same as any other file type. I can see several ways to fix this:

1. Use `scipy.io.loadmat`'s built-in `byte_order` flag. I tried this, it doesn't work.
2. Force `MatfileColumnSource` to cast data to native byte order (this is how `MatfileSource` handles things).
3. Since this isn't a problem in the pipeline generally, have `to_recarray` check byte orders and cast them to native byte order before passing to `tables` functions.

**Screenshots**

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: macOS Mojave 10.14.6
 - Python version: 3
 - numpy version: 1.16.6
- scipy version: 1.3.2
 - wxpython version [if a UI bug]:

**Additional context**

**Comment by zacsimile** [comment]
Fixed in #331.
