### ISSUE TITLE
Shaded points broken: normals aren't added to pipeline before they are queried

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#34]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/34) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

```
#!python

(VisGUI:11633): Gtk-CRITICAL **: IA__gtk_widget_set_size_request: assertion 'height >= -1' failed
0
0
Gui stuff done
New shader program created: <class 'PYME.LMVis.shader_programs.PointSpriteShaderProgram.PointSpriteShaderProgram'>
Traceback (most recent call last):
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/LMVis/visCore.py", line 288, in OnViewShadedPoints
    self.RefreshView()
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/LMVis/visCore.py", line 442, in RefreshView
    normal_x=self.pipeline['xn'],
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/LMVis/pipeline.py", line 307, in __getitem__
    return self.colourFilter[keys]
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/tabular.py", line 709, in __getitem__
    return self.get_channel_column(self.currentColour, keys)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/tabular.py", line 716, in get_channel_column
    return self.resultsSource[keys]
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/tabular.py", line 472, in __getitem__
    return self.resultsSource[key][self.Index][sl]
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/tabular.py", line 576, in __getitem__
    return self.resultsSource[keys]
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/tabular.py", line 576, in __getitem__
    return self.resultsSource[keys]
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/tabular.py", line 239, in __getitem__
    raise KeyError('Key not found - %s' % key)
KeyError: 'Key not found - xn'

```

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Thanks to Kenny for pointing this out.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Not so much broken, rather only works for very specific data sets - IE data with normals (the result of fitting a surface model). There is no easy way of calculating normals from standard data so it doesn't make sense to use it. 

We should probably either disable the mode if normals are not present, or check and then display a dialog saying that there are no normals and so the method doesn't work.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Resolved by adding an informative error message in commit 09700fd

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Perfect, thank you David.
