### ISSUE TITLE
numpy 1.9 OSX pyme conda package references numpy >1.10 functions

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#36]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/36) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

When opening an tif in dh5view:
```
#!python

/Users/Andrew/anaconda/lib/python2.7/site-packages/dask/array/numpy_compat.py:32: RuntimeWarning: divide by zero encountered in divide
  not np.allclose(np.divide(1, .5, dtype='i8'), 2) or
Traceback (most recent call last):
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 16766, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/PYME/DSView/dsviewer.py", line 408, in LoadData
    vframe = DSViewFrame(im, None, im.filename, mode = mode)
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/PYME/DSView/dsviewer.py", line 157, in __init__
    modules.loadMode(self.mode, self)
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/PYME/DSView/modules/__init__.py", line 92, in loadMode
    loadModule(m, dsviewer)
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/PYME/DSView/modules/__init__.py", line 67, in loadModule
    mod = __import__('.'.join(ml) + '.' + modName, fromlist=ml)
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/PYME/DSView/modules/recipes.py", line 30, in <module>
    from PYME.recipes import recipeGui
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/PYME/recipes/recipeGui.py", line 21, in <module>
    from PYME.recipes import modules
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/PYME/recipes/modules.py", line 21, in <module>
    from . import skfilters
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/PYME/recipes/skfilters.py", line 13, in <module>
    import skimage.filters as skf
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/skimage/__init__.py", line 158, in <module>
    from .util.dtype import *
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/skimage/util/__init__.py", line 5, in <module>
    from .apply_parallel import apply_parallel
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/skimage/util/apply_parallel.py", line 8, in <module>
    import dask.array as da
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/dask/array/__init__.py", line 15, in <module>
    from .ufunc import (add, subtract, multiply, divide, logaddexp, logaddexp2,
  File "/Users/Andrew/anaconda/lib/python2.7/site-packages/dask/array/ufunc.py", line 138, in <module>
    cbrt = ufunc(np.cbrt)
AttributeError: 'module' object has no attribute 'cbrt'
```

with:
python-microscopy: 17.01.27-np19py27_0 david_baddeley

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

How did you install?

17.01.27  is a fairly old version of PYME. That said, **we** don't call the functions - this appears to be version conflict between scikits-image and numpy (implies something broken with dependency management on a larger scale).

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

I installed using conda. That said, I think my dependencies were out of whack - uninstalling pyme and updating numpy to 1.11 called for a downgrade of the sk-image. Should you or I resolve the issue? Sorry for jumping the gun on this one.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Try installing in a clean virtual environment - this is probably the closest we get to a clean install and mimics what end users might do.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

In a clean environment, conda install python-microscopy works fine (grabbing most recent version). If I make another clean environment and install 17.01.27 (with numpy 1.9), I hit the same error as shown in the traceback above.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Only applies to an old version of PYME - probably relates to issues with conda package management
