### ISSUE TITLE
Python 3 compatibility error with VisGUI: assembling LUTs

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#38]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/38) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Will get to it at some point, but thought it best to document it here.
```
#!python

$ VisGUI
Traceback (most recent call last):
  File "/home/smeagol/anaconda3/bin/VisGUI", line 11, in <module>
    load_entry_point('PYME', 'console_scripts', 'VisGUI')()
  File "/home/smeagol/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/smeagol/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "/home/smeagol/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2405, in load
    return self.resolve()
  File "/home/smeagol/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/VisGUI.py", line 41, in <module>
    from PYME.misc import extraCMaps
  File "/home/smeagol/code/python-microscopy/PYME/misc/extraCMaps.py", line 58, in <module>
    pylab.cm.cmapnames += ncmapnames
TypeError: unsupported operand type(s) for +=: 'dict_keys' and 'dict_keys'

```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

This is vaguely familiar, and might also relate to the matplotlib version being used. That said, I think the issue is that dict.keys() returns an iterator one py3k rather than a list. It would be worth experimenting - it might be that the keys automatically update on python 3 and that this line isn't needed (can by prefaced with a test for python 2)

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

You're spot on that it returns an iterator under py3 (I played with this a bit last week but had more urgent tasks in py2).

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

I think this is fixed in a recent commit

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

I believe this is now fixed
