### ISSUE TITLE
[BUG] tiler stop race condition

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#386]
**Describe the bug**
Recent fixes in `pointScanner` (#355 #366) to call it's stop method on time have fixed things for tile_triggered type acquisitions (which now work smoothly), however there appears to be a race condition with the pyramid between the tiler's stop method, which calls `self.P.update_pyramid()` and a `tile_panel` `wx.CallAfter` which also tries to `self.scope.tiler.P.update_pyramid()` in `_launch_viewer`

```
987.1 -57.5 17182 8098 -44.753685 236.2463
988.3 -32.800000000000004 17192 8313 -63.753685 249.2463
Traceback (most recent call last):
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 235, in onExpReady
    self.onFrame.send(sender=self, frameData=d)
  File "C:\Users\Bergamot\Anaconda2\envs\pyme\lib\site-packages\dispatch\dispatcher.py", line 162, in send
    response = receiver(signal=self, sender=sender, **named)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Utils\tiler.py", line 80, in tick
    pointScanner.PointScanner.tick(self, frameData, **kwargs)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Utils\pointScanner.py", line 198, in tick
    self._stop()
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Utils\tiler.py", line 103, in _stop
    self.P.update_pyramid()
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 374, in update_pyramid
    self._rebuild_base()
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 366, in _rebuild_base
    occ = self._occ.get_tile(0, xc, yc) + 1e-9
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'
Traceback (most recent call last):
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 26, in load
    return self._cache[filename].data
KeyError: 'F:\\2020_8_3_A0_PD20_digodTAF647\\0\\036\\036_016_occ.pzf'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Bergamot\Anaconda2\envs\pyme\lib\site-packages\wx\core.py", line 2228, in Notify
    self.notify()
  File "C:\Users\Bergamot\Anaconda2\envs\pyme\lib\site-packages\wx\core.py", line 3384, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\ui\tile_panel.py", line 106, in _launch_viewer
    self.scope.tiler.P.update_pyramid()
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 374, in update_pyramid
    self._rebuild_base()
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 366, in _rebuild_base
    occ = self._occ.get_tile(0, xc, yc) + 1e-9
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 142, in get_tile
    return self._tilecache.load(self._filename(layer, x, y))
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 29, in load
    self._add(filename, data, saved=True)
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 59, in _add
    self._drop(fn)
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 65, in _drop
    item = self._cache.pop(filename)
KeyError: 'F:\\2020_8_3_A0_PD20_digodTAF647\\0\\035\\035_031_occ.pzf'
Warning: not keeping up with camera, giving up with 0 frames still in buffer
```

**To Reproduce**
1. run a tiled acquisition w/ simultaneous pyramid creation through the GUI

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10] win10
 - Python version: 3.6
 - numpy version: 1.16
 - wxpython version [if a UI bug]: 4.1

**Comment by barentine** [comment]
Would note that this race condition can be avoided by commenting out one of the `update_pyramid` calls. I seem to have clobbered it in my local repo so I can't confirm which I commented out (I suspect in `tile_panel`) but there is definitely a wrong one to comment as you can open the tileviewer while the pyramid is still being built and I think that is probably a waste of cpu

**Comment by barentine** [comment]
slightly related, possibly
```
Traceback (most recent call last):
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\site-packages\wx\core.py", line 2228, in Notify
    self.notify()
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\site-packages\wx\core.py", line 3384, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\ui\tile_panel.py", line 114, in _launch_viewer
    self.scope.tiler.P.update_pyramid()
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 455, in update_pyramid
    while self._make_layer(inputLevel) > 1:
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 437, in _make_layer
    self._imgs.save_tile(new_layer, xc, yc, tile)
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 150, in save_tile
    self._tilecache.save(self._filename(layer, x, y), data)
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 35, in save
    self._add(filename, data, saved=False)
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 61, in _add
    self._drop(fn)
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 69, in _drop
    self._save(filename, item.data)
  File "c:\users\bergamot\code\python-microscopy\PYME\Analysis\tile_pyramid.py", line 99, in _save
    os.makedirs(dirname)
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 'D:\\PK212-006\\0\\003'
```
