### ISSUE TITLE
numpy version error prevents PYME from starting

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#4]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/4) by Kyle Douglass (Bitbucket: [kmdouglass](https://bitbucket.org/kmdouglass), GitHub: [kmdouglass](https://github.com/kmdouglass)).**

----------------------------------------

Hello,
I am a first-time user of PYME but an experienced Python user.

I so far have not been able to get PYME running on my Windows 10 64-bit machine. When I run any of the following three commands

```
#!shell

dh5view -t -m lite
PYMEAcquire
VisGUI
```

I encounter the following error:

```
#!python

\lib\site-packages\matplotlib\cbook.py:137: MatplotlibDeprecationWarning: The matplotlib.delaunay module was deprecated in version 1.4. Use matplotlib.tri.Triangulation instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
RuntimeError: module compiled against API version a but this version of numpy is 9
Traceback (most recent call last):
  File "C:\Users\kmdouglass\Anaconda2\envs\PYME\Scripts\VisGUI-script.py", line 3, in <module>
    import PYME.Analysis.LMVis.VisGUI
  File "C:\Users\kmdouglass\Anaconda2\envs\PYME\lib\site-packages\PYME\Analysis\LMVis\VisGUI.py", line 30, in <module>
    from PYME.DSView.dsviewer_npy_nb import View3D
  File "C:\Users\kmdouglass\Anaconda2\envs\PYME\lib\site-packages\PYME\DSView\__init__.py", line 23, in <module>
    from dsviewer_npy_nb import View3D, ViewIm3D
  File "C:\Users\kmdouglass\Anaconda2\envs\PYME\lib\site-packages\PYME\DSView\dsviewer_npy_nb.py", line 47, in <module>
    from PYME.DSView.image import ImageStack
  File "C:\Users\kmdouglass\Anaconda2\envs\PYME\lib\site-packages\PYME\DSView\image.py", line 42, in <module>
    from PYME.Analysis.LMVis.visHelpers import ImageBounds
  File "C:\Users\kmdouglass\Anaconda2\envs\PYME\lib\site-packages\PYME\Analysis\LMVis\visHelpers.py", line 33, in <module>
    from PYME.Analysis.qHull.triangWrap import RenderTetrahedra
ImportError: numpy.core.multiarray failed to import
```

This error is the same for all three scripts. I am using an up-to-date (April 16, 2016) Anaconda Python 2.7 distribution and installed PYME in clean Anaconda environment with

```
#!shell

conda update conda
conda create -n PYME -c david_baddeley python-microscopy
```

The current numpy version installed in this environment is 1.9.3. I attached the full output of `conda list`.

Any ideas on what the problem could be? Is the correct numpy version set in the conda build script? Perhaps it's a Windows 10 issue; I can try installing on Windows 7 when I get to the lab tomorrow.

Thanks!
Kyle

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Hi Kyle,

this is an issue with binary compatibility in compiled code which uses
numpy. I currently compile against numpy 1.10, but for some reason conda
install downgrades numpy to an incompatible version.

This would seem to be an issue with conda build (or my build
configuration), which I haven't yet completely got my head around.

A (somewhat unsatisfactory) work-around is to upgrade numpy to version
1.10.x after installing python-microscopy.

Cheers

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

More Info - for some reason conda-install wants to downgrade numpy to an incompatible version.

There are 2 issues here - 1) conda build does not capture the version of numpy we're using
                                         2) we might have a dependancy on a 3rd party package which is compiled against numpy 1.9

```
#!bash



conda install --dry-run python-microscopy
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/david/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cherrypy-3.8.0             |           py27_0         592 KB
    numpy-1.9.3                |           py27_1         2.9 MB
    numexpr-2.4.4              |       np19py27_0         103 KB
    scipy-0.16.0               |       np19py27_1        12.5 MB
    matplotlib-1.4.3           |       np19py27_3        40.8 MB
    pytables-3.2.2             |       np19py27_0         1.6 MB
    scikit-learn-0.16.1        |       np19py27_0         3.3 MB
    scikit-image-0.11.3        |       np19py27_0        16.1 MB
    python-microscopy-16.04.15 |           py27_0        32.0 MB
    ------------------------------------------------------------
                                           Total:       109.8 MB

The following NEW packages will be INSTALLED:

    cherrypy:          3.8.0-py27_0     
    python-microscopy: 16.04.15-py27_0  
    toposort:          1.1-py27_0       

The following packages will be UPDATED:

    numexpr:           2.4.4-np110py27_0  --> 2.4.4-np19py27_0 
    pytables:          3.2.2-np110py27_0  --> 3.2.2-np19py27_0 
    scikit-image:      0.11.3-np110py27_0 --> 0.11.3-np19py27_0
    scipy:             0.16.0-np110py27_1 --> 0.16.0-np19py27_1

The following packages will be DOWNGRADED:

    matplotlib:        1.5.0-np110py27_0  --> 1.4.3-np19py27_3 
    numpy:             1.10.4-py27_0      --> 1.9.3-py27_1     
    scikit-learn:      0.17-np110py27_1   --> 0.16.1-np19py27_0

Dry run: exiting


```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------


```
#!bash

conda install --dry-run python-microscopy numpy=1.10
Fetching package metadata: ......
Solving package specifications: ....

The following specifications were found to be in conflict:
  - mayavi (target=mayavi-4.4.0-np19py27_0.tar.bz2) -> numpy 1.7*|1.8*|1.9*
  - pyfftw3 (target=pyfftw3-0.2.1-np19py27_2.tar.bz2) -> numpy 1.9*
  - python-microscopy -> mayavi
  - python-microscopy -> numpy 1.9*
  - python-microscopy -> pyfftw3
Use "conda info <package>" to see the dependencies for each package.

```

Problem seems to be 2 dependancies - pyfftw3 (which is being installed from my channel and I should recompile) and mayavi, which is coming from the anaconda archives in the wrong version.


```
#!bash

conda search mayavi
Fetching package metadata: ......
mayavi                       4.3.0                np17py27_0  defaults        
                             4.3.0                np17py27_1  defaults        
                             4.3.0                np17py27_2  defaults        
                             4.3.0                np17py27_3  defaults        
                             4.3.0                np17py27_4  defaults        
                             4.3.1                np18py27_0  defaults        
                             4.3.1                np18py27_1  defaults        
                             4.3.1                np19py27_1  defaults        
                          *  4.4.0                np19py27_0  defaults

```


```
#!bash

conda search pyfftw3
Fetching package metadata: ......
pyfftw3                   .  0.2.1                np19py27_0  david_baddeley  
                             0.2.1                np19py27_1  david_baddeley  
                          *  0.2.1                np19py27_2  david_baddeley

```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

**TEMPORARY SOLUTION:** Force conda build to use numpy 1.9 so as to be consistent with available Mayavi versions. New packages are available for OSX and windows.

Long-term, should try and fix dependencies so not tied to old numpy version.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Compiled against Mayavi's version of numpy (1.9), new packages available

**Comment by David-Baddeley** [comment]
**Original comment by Kyle Douglass (Bitbucket: [kmdouglass](https://bitbucket.org/kmdouglass), GitHub: [kmdouglass](https://github.com/kmdouglass)).**

----------------------------------------

That fixed it on my end, too.

Thanks!
