### ISSUE TITLE
generating jittered triangulation without "software rendering" fails

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#41]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/41) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Neither the shader nor non-shader LMGLCanvas classes have genJitTim methods
```
#!python

Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 276, in GenerateGUI
    im = self.Generate(dlg.get_settings())
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 245, in Generate
    ims.append(np.atleast_3d(self.genIm(settings, imb, mdh)))
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 411, in genIm
    return self.visFr.glCanvas.genJitTim(settings['numSamples'],self.colourFilter['x'],
AttributeError: 'LMGLCanvas' object has no attribute 'genJitTim'
```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Do we need to continue to support OpenGL rendering for the generation of images, or can we just deprecate it? The option for OpenGL rendering is mostly a legacy of very early code where we didn't have a fast way of doing it on the CPU. The software rendering has been faster for some time.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

I think depreciating it would be a good move, but OpenGL isn't something I know a lot about. I just came across it while updating the matplotlib calls and thought it would be good to flag it.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

have now removed software rendering option from GUI, so that you can't unselect it.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

GL rendering has been deprecated, now removed from GUI
