### ISSUE TITLE
[BUG] ClusterOfOne doesn't pick up data on Windows outside of PYMEDATADIR

### ISSUE THREAD

**Issue by khu6** [python-microscopy/python-microscopy#419]
```
ERROR:root:127.0.0.1 - - [17/Aug/2020 15:46:16] code 404, message File not found - /C:Userskh725Downloads/analysis/, [C:\Users\kh725\PYMEData\analysis/]

ERROR:root:127.0.0.1 - - [17/Aug/2020 15:46:16] code 404, message File not found - /C:Userskh725Downloads/analysis/, [C:\Users\kh725\PYMEData\analysis/]

ERROR:root:127.0.0.1 - - [17/Aug/2020 15:46:16] code 404, message File not found - /C:Userskh725Downloads/analysis/, [C:\Users\kh725\PYMEData\analysis/]

ERROR:root:127.0.0.1 - - [17/Aug/2020 15:46:16] code 404, message File not found - /C:Userskh725Downloads/analysis/, [C:\Users\kh725\PYMEData\analysis/]

ERROR:root:127.0.0.1 - - [17/Aug/2020 15:46:16] code 404, message File not found - /C:Userskh725Downloads/analysis/, [C:\Users\kh725\PYMEData\analysis/]

ERROR:root:127.0.0.1 - - [17/Aug/2020 15:46:16] code 404, message File not found - /C:Userskh725Downloads/analysis/, [C:\Users\kh725\PYMEData\analysis/]

DEBUG:root:pytables open call: C:\Users\kh725\PYMEData\analysis\0_000_000.h5r
DEBUG:root:pytables file open: C:\Users\kh725\PYMEData\analysis\0_000_000.h5r
DEBUG:root:H5RFile - closing: C:\Users\kh725\PYMEData\analysis\0_000_000.h5r
DEBUG:root:H5RFile - closed: C:\Users\kh725\PYMEData\analysis\0_000_000.h5r


ERROR:PYME.IO.unifiedIO:Name "C:\Users\kh725\Downloads/analysis/0_000_000.h5r" is invalid. Names must only include alphanumeric characters and underscore
DEBUG:PYME.IO.clusterIO:Request for b'http://127.0.0.1:49831/C:Userskh725Downloads/analysis/' failed with error: 404
DEBUG:PYME.IO.clusterIO:Request for b'http://127.0.0.1:49859/C:Userskh725Downloads/analysis/' failed with error: 404
DEBUG:PYME.IO.clusterIO:Request for b'http://127.0.0.1:49859/C:Userskh725Downloads/analysis/' failed with error: 404
DEBUG:PYME.IO.clusterIO:Request for b'http://127.0.0.1:49831/C:Userskh725Downloads/analysis/' failed with error: 404
DEBUG:root:Results file: C:Userskh725Downloads/analysis/0_000_000.h5r
DEBUG:PYME.IO.clusterIO:Request for b'http://127.0.0.1:49831/C:Userskh725Downloads/analysis/' failed with error: 404
DEBUG:PYME.IO.clusterIO:Request for b'http://127.0.0.1:49859/C:Userskh725Downloads/analysis/' failed with error: 404
NSInfo(name='PYMERuleServer: P9X79EWS', address=b'\x7f\x00\x00\x01', port=49857, creation_time=1597693539.2598615, URI='') b'\x7f\x00\x00\x01'
DEBUG:PYME.cluster.HTTPRulePusher:local_queues: ['PYMERuleServer: P9X79EWS']
DEBUG:PYME.cluster.HTTPRulePusher:DataSource.__class__: <class 'PYME.IO.DataSources.DcimgDataSource.DataSource'>
DEBUG:root:resultsURI: http://127.0.0.1:49831/__aggregate_h5r/C:Userskh725Downloads/analysis/0_000_000.h5r
DEBUG:root:fileFormattedResults - URI: http://127.0.0.1:49831/__aggregate_h5r/C:Userskh725Downloads/analysis/0_000_000.h5r/MetaData
WARNING:root:No handler for data type found, using pickle
DEBUG:root:fileFormattedResults - URI: http://127.0.0.1:49831/__aggregate_h5r/C:Userskh725Downloads/analysis/0_000_000.h5r/Events
Traceback (most recent call last):
  File "c:\users\kh725\python-microscopy\PYME\IO\unifiedIO.py", line 49, in assert_name_ok
    assert check_name(name) == True
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\kh725\python-microscopy\PYME\DSView\modules\LMAnalysis.py", line 266, in <lambda>
    self.bGo.Bind(wx.EVT_BUTTON, lambda e : self.lmanal.OnGo(e))
  File "c:\users\kh725\python-microscopy\PYME\DSView\modules\LMAnalysis.py", line 660, in OnGo
    self.analysisController.pushImagesCluster(self.image)
  File "c:\users\kh725\python-microscopy\PYME\DSView\modules\LMAnalysis.py", line 341, in pushImagesCluster
    metadata=self.resultsMdh, resultsFilename=resultsFilename)
  File "c:\users\kh725\python-microscopy\PYME\cluster\HTTPRulePusher.py", line 191, in __init__
    clusterIO.put_file(resultsMDFilename, self.mdh.to_JSON().encode(), serverfilter=serverfilter)
  File "c:\users\kh725\python-microscopy\PYME\IO\clusterIO.py", line 961, in put_file
    unifiedIO.assert_name_ok(filename)
  File "c:\users\kh725\python-microscopy\PYME\IO\unifiedIO.py", line 51, in assert_name_ok
    raise AssertionError('Name "%s" is invalid. Names must only include alphanumeric characters and underscore' % name)
AssertionError: Name "C:Userskh725Downloads/analysis/0_000_000.h5r.json" is invalid. Names must only include alphanumeric characters and underscore
```

To reproduce:
Start PYMEClusterOfOne
From dh5view, queue any localization analysis on a file somewhere other than PYMEDATADIR

Windows 10
Python 3.6.10
PYME 20.04.25

**Comment by David-Baddeley** [comment]
hmm, this looks like an `os.sep` issue (although it's a bit more complex -  seems string escaping is also not working on the backslashes).
