### ISSUE TITLE
[BUG] slicesUsed error in fitInfo for GPU fit on multiview metadata

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#454]
**Describe the bug**
```
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/DSView/modules/LMAnalysis.py", line 818, in update
    self.fitInf.UpdateDisp(self.view.PointsHitTest())
  File "/home/smeagol/code/python-microscopy/PYME/DSView/fitInfo.py", line 157, in UpdateDisp
    self.fitViewPan.draw(index)
  File "/home/smeagol/code/python-microscopy/PYME/DSView/fitInfo.py", line 414, in draw
    imd = self._extractROI(fri)
  File "/home/smeagol/code/python-microscopy/PYME/DSView/fitInfo.py", line 310, in _extractROI
    return self.ds[slice(*fri['slicesUsed']['x']), slice(*fri['slicesUsed']['y']), int(fri['tIndex'])].squeeze()
ValueError: no field of name slicesUsed
```

Clicking on a point still displays fit info, but no plots and the above traceback is thrown in the console.

**To Reproduce**
1. load blinking data with multiview metadata, select AstigGaussGPUFitFR
2. Click on 'Test This Frame`
3. Move the FitInfo tab somewhere you can click/see easy (maybe other people don't do this, but I think it's way more useful if its on the same page)
4. look at the console and notice there's a traceback and probably something else was supposed to happen too

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10]
ubuntu 16.04
 - Python version:
3.6
 - numpy version:
1.16
 - wxpython version [if a UI bug]:
4.0.4

**Additional context**
haven't looked at it yet but filing so I don't forget

**Comment by barentine** [comment]
![image](https://user-images.githubusercontent.com/31105780/94267780-255f9b80-ff0a-11ea-922f-ee8e42a0b19c.png)
