### ISSUE TITLE
installation fails due to cython error in octree code

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#46]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/46) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

With cython version 0.25.2, development install of PYME (latest commit: fd5900d38baa) results in the following traceback. This does not happen with versions before commit 29b19df5a5cc where the octree code was first introduced.

```
#!python

:~/code/python-microscopy$ python setup.py develop
Warning: Assuming default configuration (PYME/Analysis/points/QuadTree/{setup_QuadTree,setup}.py was not found)Appending PYME.PYME.Analysis.points.QuadTree configuration to PYME.PYME.Analysis.points
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis.points' to 'PYME.PYME.Analysis.points.QuadTree')
Appending PYME.PYME.Analysis.points.SoftRend configuration to PYME.PYME.Analysis.points
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis.points' to 'PYME.PYME.Analysis.points.SoftRend')
Appending PYME.PYME.Analysis.points.DistHist configuration to PYME.PYME.Analysis.points
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis.points' to 'PYME.PYME.Analysis.points.DistHist')
Appending PYME.PYME.Analysis.points.DeClump configuration to PYME.PYME.Analysis.points
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis.points' to 'PYME.PYME.Analysis.points.DeClump')
Appending PYME.PYME.Analysis.points.EdgeDB configuration to PYME.PYME.Analysis.points
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis.points' to 'PYME.PYME.Analysis.points.EdgeDB')
Appending PYME.PYME.Analysis.points.arcfit configuration to PYME.PYME.Analysis.points
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis.points' to 'PYME.PYME.Analysis.points.arcfit')
Appending PYME.PYME.Analysis.points.astigmatism configuration to PYME.PYME.Analysis.points
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis.points' to 'PYME.PYME.Analysis.points.astigmatism')
Appending PYME.PYME.Analysis.points configuration to PYME.PYME.Analysis
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis' to 'PYME.PYME.Analysis.points')
Warning: Assuming default configuration (PYME/Analysis/BleachProfile/{setup_BleachProfile,setup}.py was not found)Appending PYME.PYME.Analysis.BleachProfile configuration to PYME.PYME.Analysis
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis' to 'PYME.PYME.Analysis.BleachProfile')
Warning: Assuming default configuration (PYME/Analysis/Colocalisation/{setup_Colocalisation,setup}.py was not found)Appending PYME.PYME.Analysis.Colocalisation configuration to PYME.PYME.Analysis
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis' to 'PYME.PYME.Analysis.Colocalisation')
Warning: Assuming default configuration (PYME/Analysis/Tracking/{setup_Tracking,setup}.py was not found)Appending PYME.PYME.Analysis.Tracking configuration to PYME.PYME.Analysis
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis' to 'PYME.PYME.Analysis.Tracking')
Warning: Assuming default configuration (PYME/Analysis/PSFEst/{setup_PSFEst,setup}.py was not found)Appending PYME.PYME.Analysis.PSFEst configuration to PYME.PYME.Analysis
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis' to 'PYME.PYME.Analysis.PSFEst')
Appending PYME.PYME.Analysis.PSFGen configuration to PYME.PYME.Analysis
Ignoring attempt to set 'name' (from 'PYME.PYME.Analysis' to 'PYME.PYME.Analysis.PSFGen')
Appending PYME.PYME.Analysis configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.Analysis')
Warning: Assuming default configuration (PYME/Acquire/Hardware/AndorIXon/{setup_AndorIXon,setup}.py was not found)Appending PYME.PYME.Acquire.Hardware.AndorIXon configuration to PYME.PYME.Acquire.Hardware
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire.Hardware' to 'PYME.PYME.Acquire.Hardware.AndorIXon')
Warning: Assuming default configuration (PYME/Acquire/Hardware/AndorNeo/{setup_AndorNeo,setup}.py was not found)Appending PYME.PYME.Acquire.Hardware.AndorNeo configuration to PYME.PYME.Acquire.Hardware
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire.Hardware' to 'PYME.PYME.Acquire.Hardware.AndorNeo')
Warning: Assuming default configuration (PYME/Acquire/Hardware/DigiData/{setup_DigiData,setup}.py was not found)Appending PYME.PYME.Acquire.Hardware.DigiData configuration to PYME.PYME.Acquire.Hardware
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire.Hardware' to 'PYME.PYME.Acquire.Hardware.DigiData')
Warning: Extension name 'PYME.PYME.Acquire.Hardware.Simulator.illuminate' does not match fully qualified name 'PYME.Acquire.Hardware.Simulator.illuminate' of 'PYME/Acquire/Hardware/Simulator/illuminate.pyx'
Appending PYME.PYME.Acquire.Hardware.Simulator configuration to PYME.PYME.Acquire.Hardware
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire.Hardware' to 'PYME.PYME.Acquire.Hardware.Simulator')
Warning: Assuming default configuration (PYME/Acquire/Hardware/Old/{setup_Old,setup}.py was not found)Appending PYME.PYME.Acquire.Hardware.Old configuration to PYME.PYME.Acquire.Hardware
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire.Hardware' to 'PYME.PYME.Acquire.Hardware.Old')
Warning: Assuming default configuration (PYME/Acquire/Hardware/Piezos/{setup_Piezos,setup}.py was not found)Appending PYME.PYME.Acquire.Hardware.Piezos configuration to PYME.PYME.Acquire.Hardware
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire.Hardware' to 'PYME.PYME.Acquire.Hardware.Piezos')
Appending PYME.PYME.Acquire.Hardware configuration to PYME.PYME.Acquire
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire' to 'PYME.PYME.Acquire.Hardware')
Warning: Assuming default configuration (PYME/Acquire/Protocols/{setup_Protocols,setup}.py was not found)Appending PYME.PYME.Acquire.Protocols configuration to PYME.PYME.Acquire
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire' to 'PYME.PYME.Acquire.Protocols')
Warning: Assuming default configuration (PYME/Acquire/ui/{setup_ui,setup}.py was not found)Appending PYME.PYME.Acquire.ui configuration to PYME.PYME.Acquire
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire' to 'PYME.PYME.Acquire.ui')
Warning: Assuming default configuration (PYME/Acquire/Utils/{setup_Utils,setup}.py was not found)Appending PYME.PYME.Acquire.Utils configuration to PYME.PYME.Acquire
Ignoring attempt to set 'name' (from 'PYME.PYME.Acquire' to 'PYME.PYME.Acquire.Utils')
Appending PYME.PYME.Acquire configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.Acquire')
Appending PYME.PYME.DSView.LUT configuration to PYME.PYME.DSView
Ignoring attempt to set 'name' (from 'PYME.PYME.DSView' to 'PYME.PYME.DSView.LUT')
Warning: Assuming default configuration (PYME/DSView/modules/{setup_modules,setup}.py was not found)Appending PYME.PYME.DSView.modules configuration to PYME.PYME.DSView
Ignoring attempt to set 'name' (from 'PYME.PYME.DSView' to 'PYME.PYME.DSView.modules')
Appending PYME.PYME.DSView configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.DSView')
Warning: Assuming default configuration (PYME/ParallelTasks/{setup_ParallelTasks,setup}.py was not found)Appending PYME.PYME.ParallelTasks configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.ParallelTasks')
Warning: Extension name 'PYME.PYME.buffer_helpers' does not match fully qualified name 'PYME.IO.buffer_helpers' of 'PYME/IO/buffer_helpers.pyx'
Appending PYME.PYME.IO.FileUtils configuration to PYME.PYME.IO
Ignoring attempt to set 'name' (from 'PYME.PYME.IO' to 'PYME.PYME.IO.FileUtils')
Warning: Assuming default configuration (PYME/IO/DataSources/{setup_DataSources,setup}.py was not found)Appending PYME.PYME.IO.DataSources configuration to PYME.PYME.IO
Ignoring attempt to set 'name' (from 'PYME.PYME.IO' to 'PYME.PYME.IO.DataSources')
Appending PYME.PYME.IO.countdir configuration to PYME.PYME.IO
Ignoring attempt to set 'name' (from 'PYME.PYME.IO' to 'PYME.PYME.IO.countdir')
Appending PYME.PYME.IO configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.IO')
Warning: Assuming default configuration (PYME/Deconv/{setup_Deconv,setup}.py was not found)Appending PYME.PYME.Deconv configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.Deconv')
Warning: Assuming default configuration (PYME/misc/{setup_misc,setup}.py was not found)Appending PYME.PYME.misc configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.misc')
Warning: Assuming default configuration (PYME/LMVis/Extras/{setup_Extras,setup}.py was not found)Appending PYME.PYME.LMVis.Extras configuration to PYME.PYME.LMVis
Ignoring attempt to set 'name' (from 'PYME.PYME.LMVis' to 'PYME.PYME.LMVis.Extras')
Warning: Assuming default configuration (PYME/LMVis/layers/{setup_layers,setup}.py was not found)Appending PYME.PYME.LMVis.layers configuration to PYME.PYME.LMVis
Ignoring attempt to set 'name' (from 'PYME.PYME.LMVis' to 'PYME.PYME.LMVis.layers')
Warning: Assuming default configuration (PYME/LMVis/shader_programs/{setup_shader_programs,setup}.py was not found)Appending PYME.PYME.LMVis.shader_programs configuration to PYME.PYME.LMVis
Ignoring attempt to set 'name' (from 'PYME.PYME.LMVis' to 'PYME.PYME.LMVis.shader_programs')
Appending PYME.PYME.LMVis configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.LMVis')
Warning: Assuming default configuration (PYME/ui/{setup_ui,setup}.py was not found)Appending PYME.PYME.ui configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.ui')
Warning: Assuming default configuration (PYME/util/{setup_util,setup}.py was not found)Appending PYME.PYME.util configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.util')
Warning: Assuming default configuration (PYME/util/shmarray/{setup_util.shmarray,setup}.py was not found)Appending PYME.PYME.util.shmarray configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.util.shmarray')
Warning: Assuming default configuration (PYME/util/mProfile/{setup_util.mProfile,setup}.py was not found)Appending PYME.PYME.util.mProfile configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.util.mProfile')
Warning: Assuming default configuration (PYME/util/fProfile/{setup_util.fProfile,setup}.py was not found)Appending PYME.PYME.util.fProfile configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.util.fProfile')
Appending PYME.PYME.localization.cModels configuration to PYME.PYME.localization
Ignoring attempt to set 'name' (from 'PYME.PYME.localization' to 'PYME.PYME.localization.cModels')
Appending PYME.PYME.localization.cInterp configuration to PYME.PYME.localization
Ignoring attempt to set 'name' (from 'PYME.PYME.localization' to 'PYME.PYME.localization.cInterp')
Warning: Assuming default configuration (PYME/localization/FitFactories/{setup_FitFactories,setup}.py was not found)Appending PYME.PYME.localization.FitFactories configuration to PYME.PYME.localization
Ignoring attempt to set 'name' (from 'PYME.PYME.localization' to 'PYME.PYME.localization.FitFactories')
Warning: Assuming default configuration (PYME/localization/FitFactories/Interpolators/{setup_FitFactories.Interpolators,setup}.py was not found)Appending PYME.PYME.localization.FitFactories.Interpolators configuration to PYME.PYME.localization
Ignoring attempt to set 'name' (from 'PYME.PYME.localization' to 'PYME.PYME.localization.FitFactories.Interpolators')
Warning: Assuming default configuration (PYME/localization/FitFactories/zEstimators/{setup_FitFactories.zEstimators,setup}.py was not found)Appending PYME.PYME.localization.FitFactories.zEstimators configuration to PYME.PYME.localization
Ignoring attempt to set 'name' (from 'PYME.PYME.localization' to 'PYME.PYME.localization.FitFactories.zEstimators')
Warning: Assuming default configuration (PYME/localization/autopsf/{setup_autopsf,setup}.py was not found)Appending PYME.PYME.localization.autopsf configuration to PYME.PYME.localization
Ignoring attempt to set 'name' (from 'PYME.PYME.localization' to 'PYME.PYME.localization.autopsf')
Appending PYME.PYME.localization configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.localization')
Appending PYME.PYME.recipes configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.recipes')
Appending PYME.PYME.resources configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.resources')
Warning: Assuming default configuration (PYME/contrib/pad/{setup_pad,setup}.py was not found)Appending PYME.PYME.contrib.pad configuration to PYME.PYME.contrib
Ignoring attempt to set 'name' (from 'PYME.PYME.contrib' to 'PYME.PYME.contrib.pad')
Appending PYME.PYME.contrib.gohlke configuration to PYME.PYME.contrib
Ignoring attempt to set 'name' (from 'PYME.PYME.contrib' to 'PYME.PYME.contrib.gohlke')
Warning: Assuming default configuration (PYME/contrib/aniso/{setup_aniso,setup}.py was not found)Appending PYME.PYME.contrib.aniso configuration to PYME.PYME.contrib
Ignoring attempt to set 'name' (from 'PYME.PYME.contrib' to 'PYME.PYME.contrib.aniso')
Appending PYME.PYME.contrib configuration to PYME.PYME
Ignoring attempt to set 'name' (from 'PYME.PYME' to 'PYME.PYME.contrib')
Warning: Extension name 'PYME.PYME._octree' does not match fully qualified name 'PYME.experimental._octree' of 'PYME/experimental/_octree.pyx'
Compiling PYME/experimental/_octree.pyx because it changed.
[1/1] Cythonizing PYME/experimental/_octree.pyx
warning: PYME/experimental/_octree.pyx:209:20: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: PYME/experimental/_octree.pyx:209:31: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.

Error compiling Cython file:
------------------------------------------------------------
...

cdef extern from *:
    object PyErr_Format(exc, const char *format, ...)

@cname("__Pyx_carray_from_py_float32__t")
cdef int __Pyx_carray_from_py_float32__t(object o, float32_t *v, Py_ssize_t length) except -1:
                                                  ^
------------------------------------------------------------

carray.from_py:77:51: 'float32_t' is not a type identifier
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    conf = configuration(top_path='').todict()
  File "setup.py", line 18, in configuration
    config.add_subpackage('PYME')
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1000, in add_subpackage
    caller_level = 2)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 969, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 906, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "./PYME/setup.py", line 58, in configuration
    config.add_subpackage('experimental')
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1000, in add_subpackage
    caller_level = 2)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 969, in get_subpackage
    caller_level = caller_level + 1)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 906, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "PYME/experimental/setup.py", line 46, in configuration
    config = Configuration('experimental', parent_package, top_path, ext_modules=cythonize([ext]))
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 934, in cythonize
    cythonize_one(*args)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 1056, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: PYME/experimental/_octree.pyx

```

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Not a bug with PYME, can be fixed by updating cython: 0.25.2 --> 0.28.3
