### ISSUE TITLE
[ENHANCEMENT/BUGFIX]: FitPoints traits don't include (base) fit module defaults

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#467]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when I think we can localize cleanly in a recipe and then remember we can't

At the moment we don't grab any (base) fit factory defaults into the metadata, resulting in stuff like
```
ERROR:PYME.recipes.base:Error in recipe module: <PYME.recipes.measurement.FitPoints object at 0x7f685b7b1a98>
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 641, in execute
    m.execute(self.namespace)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/measurement.py", line 229, in execute
    r[i] = ff.FromPoint(x/ps, y/ps, roiHalfSize=self.roiHalfSize)
  File "/home/smeagol/code/python-microscopy/PYME/localization/FitFactories/AstigGaussGPUFitFR.py", line 285, in FromPoint
    self.refresh_warpdrive(camera_maps)
  File "/home/smeagol/code/python-microscopy/PYME/localization/FitFactories/AstigGaussGPUFitFR.py", line 165, in refresh_warpdrive
    small_filter_size = self.metadata.getEntry('Analysis.DetectionFilterSize')
  File "/home/smeagol/code/python-microscopy/PYME/IO/MetaDataHandler.py", line 547, in getEntry
    return eval('self.'+entryName)
  File "<string>", line 1, in <module>
AttributeError: 'NestedClassMDHandler' object has no attribute 'Analysis'
```

**Describe the solution you'd like**
- add a `settings` `DictStrAny` param to `FitPoints`
- refactor `DEFAULT_PARAMS` out of the analysis setting panel and into the module so we can import it
- pull in DEFAULT_PARAMS and fitMod.PARAMETERS in a custom `FitPoints._view_items` to fill `settings` so one can localize as normal from a recipe.

**Describe alternatives you've considered**
not using recipes for localization

**Are you prepared to work on it?**
started to, but stopping to check in before continuing

**Comment by David-Baddeley** [comment]
I think we've hit this with #1415
