### ISSUE TITLE
webdav can time out when connection is started

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#47]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/47) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Client gets "Sorry, could not display all the contents of “/”: HTTP Error: Message Corrupt".

Traceback from webdav:

```
#!python

INFO:__main__:censured.102 - - [17/Jun/2018 14:06:37] "OPTIONS / HTTP/1.1" 401 -

INFO:__main__:censured.102 - - [17/Jun/2018 14:06:56] "OPTIONS / HTTP/1.1" 200 -

INFO:__main__:censured.102 - - [17/Jun/2018 14:06:56] "PROPFIND / HTTP/1.1" 207 -

<?xml version="1.0" encoding="utf-8" ?>
<D:multistatus xmlns:D="DAV:" xmlns:Z="urn:schemas-microsoft-com:">
<D:response>
<D:href>/</D:href>
<D:propstat>
<D:prop>
  <D:resourcetype><D:collection/></D:resourcetype>
  <D:getcontentlength>0</D:getcontentlength>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
</D:multistatus>INFO:__main__:censured.102 - - [17/Jun/2018 14:06:56] "PROPFIND / HTTP/1.1" 207 -

<?xml version="1.0" encoding="utf-8" ?>
<D:multistatus xmlns:D="DAV:" xmlns:Z="urn:schemas-microsoft-com:">
<D:response>
<D:href>/</D:href>
<D:propstat>
<D:prop>
  <D:creationdate>2018-06-17T14:06:56+00:00</D:creationdate>
  <D:getetag>6666cd76f96956469e7be39d750cc7d9</D:getetag>
  <D:resourcetype><D:collection/></D:resourcetype>
  <D:getcontenttype>httpd/unix-directory</D:getcontenttype>
  <D:getlastmodified>Sun, 17 Jun 2018 14:06:56 GMT</D:getlastmodified>
  <D:displayname>/</D:displayname>
  <D:getcontentlength>0</D:getcontentlength>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
</D:multistatus>INFO:__main__:censured.102 - - [17/Jun/2018 14:06:56] "PROPFIND / HTTP/1.1" 207 -

<?xml version="1.0" encoding="utf-8" ?>
<D:multistatus xmlns:D="DAV:" xmlns:Z="urn:schemas-microsoft-com:">
<D:response>
<D:href>/</D:href>
<D:propstat>
<D:prop>
  <D:creationdate>2018-06-17T14:06:56+00:00</D:creationdate>
  <D:getetag>6666cd76f96956469e7be39d750cc7d9</D:getetag>
  <D:resourcetype><D:collection/></D:resourcetype>
  <D:getcontenttype>httpd/unix-directory</D:getcontenttype>
  <D:getlastmodified>Sun, 17 Jun 2018 14:06:56 GMT</D:getlastmodified>
  <D:displayname>/</D:displayname>
  <D:getcontentlength>0</D:getcontentlength>
</D:prop>
<D:status>HTTP/1.1 200 OK</D:status>
</D:propstat>
</D:response>
ERROR:PYME.IO.clusterIO:Timeout on listing directory
Traceback (most recent call last):
  File "PYME/IO/clusterIO.py", line 126, in _listSingleDir
    r = s.get(url, timeout=timeout)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='censured.59', port=8080): Read timed out. (read timeout=5)
INFO:PYME.IO.clusterIO:0 retries left
----------------------------------------
Exception happened during processing of request from ('censured.102', 59372)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/ubuntu/python-microscopy/PYME/ParallelTasks/webdav.py", line 1062, in finish_request
    HTTPServer.finish_request(self, request, client_address)
  File "/home/ubuntu/anaconda2/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/ubuntu/anaconda2/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/home/ubuntu/anaconda2/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/home/ubuntu/anaconda2/lib/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "/home/ubuntu/python-microscopy/PYME/ParallelTasks/webdav.py", line 842, in do_PROPFIND
    for m in elem.getMembers():
  File "/home/ubuntu/python-microscopy/PYME/ParallelTasks/webdav.py", line 226, in getMembers
    m = DirCollection(self.fsname + fn, self.virname + fn, self) # Member is a collection
  File "/home/ubuntu/python-microscopy/PYME/ParallelTasks/webdav.py", line 189, in __init__
    if not clusterIO.exists(fsdir):
  File "PYME/IO/clusterIO.py", line 387, in exists
    return (len(locateFile(name, serverfilter, True)) > 0) or isdir(name, serverfilter)
  File "PYME/IO/clusterIO.py", line 238, in locateFile
    dirList, dt = _listSingleDir(dirurl)
  File "PYME/IO/clusterIO.py", line 126, in _listSingleDir
    r = s.get(url, timeout=timeout)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 499, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPConnectionPool(host='censured.59', port=8080): Read timed out. (read timeout=5)
----------------------------------------


```

Possible solution would be to extend the timeouts - I don't think that would be an issue for webdav like it would for sharding/analysis

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Note that this might not be an issue if DataServers only have access to directories which are chunked

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Should be addressed by PR #156

**Comment by zacsimile** [comment]
It seems like this was fixed, although not by #156, but by https://bitbucket.org/david_baddeley/python-microscopy/pull-requests/156/.

**Comment by David-Baddeley** [comment]
that would be using the bitbucket PR numbering - as far as I know it hasn't been fixed, just no-one has actually used the webdav stuff for ages. I believe the PR in question wasn't accepted because it would have had other adverse effects on clusterIO.

**Comment by David-Baddeley** [comment]
Will close as I don't think anyone cares enough about it.
