### ISSUE TITLE
Substituting sys.maxsize for sys.maxint does not work in some wx calls

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#51]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/51) by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

I've modified this to better define the problem, as reverting to sys.maxint everywhere is not an acceptable solution.

```
#!python

Traceback (most recent call last):
  File "c:\users\bdr25\python-microscopy\PYME\LMVis\visCore.py", line 377, in OnOpenFile
    self.OpenFile(filename)
  File "c:\users\bdr25\python-microscopy\PYME\LMVis\visCore.py", line 677, in OpenFile
    self.CreateFoldPanel()
  File "c:\users\bdr25\python-microscopy\PYME\ui\AUIFrame.py", line 119, in CreateFoldPanel
    genFcn(self.sidePanel)
  File "c:\users\bdr25\python-microscopy\PYME\LMVis\visCore.py", line 144, in GenPanels
    self.filterPane = CreateFilterPane(sidePanel, self.pipeline.filterKeys, self.pipeline, self)
  File "c:\users\bdr25\python-microscopy\PYME\LMVis\filterPane.py", line 33, in CreateFilterPane
    pane = FilterPane(panel, mapping, pipeline, visFr)
  File "c:\users\bdr25\python-microscopy\PYME\LMVis\filterPane.py", line 240, in __init__
    self.pFilter = FilterPanel(self, filterKeys, pipeline.selectedDataSource)
  File "c:\users\bdr25\python-microscopy\PYME\LMVis\filterPane.py", line 67, in __init__
    self.populate()
  File "c:\users\bdr25\python-microscopy\PYME\LMVis\filterPane.py", line 99, in populate
    ind = self.lFiltKeys.InsertStringItem(sys.maxsize, key)
  File "C:\Users\bdr25\AppData\Local\Continuum\anaconda2\lib\site-packages\wx-3.0-msw\wx\_controls.py", line 4713, in InsertStringItem
    return _controls_.ListCtrl_InsertStringItem(*args, **kwargs)
OverflowError: Python int too large to convert to C long
```

* Appears to only effect windows platform

**Open questions:**

* is this common to all windows installs?
* are the effected installations 64 bit?
* does it effect any other bits of code than the given traceback (i.e. do we need to find out why this is happening, or can we just patch / workaround this one occurrence) 

I believe that the code in question just needs the insertion index to be larger than the concievable maximum number of items, so we could probably substitute any large int and have it work. We certainly do not need to replace all references to sys.maxsize.

**Original issue report below:**

Calls to sys.maxsize do not work for integer comparisons in Python 2 on Windows. If 
PYME is running in a Python 2 environment, all calls to sys.maxsize must be replaced 
with calls to sys.maxint. Possible permanent fixes include

- An if statement based on the Python version
- Explicitly cast sys.maxsize to an integer. However, the value returned by sys.maxsize 
may be incorrect in Python 2 (it seems correct, though) and this might not work.

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

Thanks to @BenRollins for testing this out.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

This seems unusual. In general you should be able to assume that sys.maxsize=sys.maxint, and changing everything to sys.maxsize is the officially sanctioned way of making code run on both python 2.x and 3.x.

* Does this effect all windows systems? I'm pretty sure I've seen cases where it doesn't.
* What are the values of the following on a system that has shown the errors:

```
#!python

sys.maxsize
sys.maxint
sys.version
sys.platform
```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

This should also be altered to make it clear that this is an issue relating to wxpython (not any other uses of sys.maxsize)

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

Ran this on a new Windows 10 install. Received the following traceback.


```
#!python

Creating Pipeline
Pipeline Created
DEBUG:PYME.LMVis.VisGUI:Creating tabs
0
DEBUG:PYME.LMVis.VisGUI:Finished creating tabs
Traceback (most recent call last):
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\visCore.py", line 377, in OnOpenFile
    self.OpenFile(filename)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\visCore.py", line 677, in OpenFile
    self.CreateFoldPanel()
  File "c:\users\zrc4\documents\python-microscopy\PYME\ui\AUIFrame.py", line 119, in CreateFoldPanel
    genFcn(self.sidePanel)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\visCore.py", line 144, in GenPanels
    self.filterPane = CreateFilterPane(sidePanel, self.pipeline.filterKeys, self.pipeline, self)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py", line 33, in CreateFilterPane
    pane = FilterPane(panel, mapping, pipeline, visFr)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py", line 240, in __init__
    self.pFilter = FilterPanel(self, filterKeys, pipeline.selectedDataSource)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py", line 67, in __init__
    self.populate()
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py", line 99, in populate
    ind = self.lFiltKeys.InsertStringItem(sys.maxsize, key)
  File "C:\Users\zrc4\AppData\Local\conda\conda\envs\pyme_test\lib\site-packages\wx-3.0-msw\wx\_controls.py", line 4713, in InsertStringItem
    return _controls_.ListCtrl_InsertStringItem(*args, **kwargs)
OverflowError: Python int too large to convert to C long
```

This can be fixed by a find/replace in directory where we swap sys.maxsize for sys.maxint. Files changed are eossdk.py, SpoolController.py, filterPan.py, clusterAnalysis.py, colourPanel.py, filterPane.py, TextCtrlAutoComplete.py.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

I'd advise strongly against doing a find-replace in directory. 

workaround for the original traceback in commit ba0780c

Does this actually effect the other files?

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Marking this as closed, as I think we've hit all the wxpython uses and don't see argument that this is an issue for any of the other modules.
