### ISSUE TITLE
[BUG] Occasional dcam unbuffered error when spooling pointScanner protocols

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#517]
**Describe the bug**
Sometimes the pointscanner tick fails during tiling series (have only seen this when running through protocols spooling to cluster, not through Tiler which saves local).
```
DEBUG:PYME.IO.clusterIO:Request for b'http://10.150.7.4:15348/Bergamot/2020_8_13/EMC0103S2/000/' failed with error: 404
DEBUG:PYME.Acquire.Hardware.Camera:setting chip ROI
-128361 128361 -1
(1597343378, 44004) 62824 0
DEBUG:PYME.Acquire.Hardware.HamamatsuDCAM.HamamatsuORCA:Setting ROI: x0 744.0, y0 896.0, w 256.0, h 256.0
Traceback (most recent call last):
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 227, in onExpReady
    d = self.getFrame()
DEBUG:PYME.Acquire.Spooler:Disconnecting from frame source
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 198, in getFrame
    self.cam.ExtractColor(cs,0)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Hardware\Camera.py", line 1038, in ExtractColor
    self.camera_class.ExtractColor(self, self.chip_data, mode)
DEBUG:PYME.Acquire.Spooler:Frame source should be disconnected
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Hardware\HamamatsuDCAM\HamamatsuORCA.py", line 300, in ExtractColor
    raise DCAMZeroBufferedException()
PYME.Acquire.Hardware.HamamatsuDCAM.HamamatsuORCA.DCAMZeroBufferedException
```

Question is - is this really an issue with the camera, or are we hitting performance issues somewhere else. We can/should make this more robust, but nervous about why I haven't seen this before when saving to disk, and quick gui lock-ups every ~1 or 1.5 s

**To Reproduce**
1. `PYMEAcquire -i init_htsms.py`
2. run the `htsms-tile.py` protocol
3. sometimes around frame ~1000 you'll get a hang up where it throws the above exception
4. Can restart the tick by a `scope.cam.FireSoftwareTrigger`. Kicking it in this way lets you finish out the protocol series

**Expected behavior**
not lock up

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10] win10
 - Python version: 3.6
 - numpy version: 1.19
 - wxpython version [if a UI bug]: 4.0.4

**Comment by barentine** [comment]
unfortunately still bumping into this. so far have only gotten 4 tiles in, max, but have also hit it on well 1, and with an interesting frame displayed

![image](https://user-images.githubusercontent.com/31105780/98043994-2e3e6980-1df4-11eb-95de-d238723f291b.png)


```
DEBUG:htsms-tile:Circular tiler target radius in units of (overlapped) FOVs: 9

DEBUG:PYME.Acquire.Utils.pointScanner:Current positions: {'x': 0.0, 'x_target': 0.0, 'y': -346.0, 'y_target': -346.0, 'z': 49.97460000000008, 'z_target': 50.0}

DEBUG:PYME.Acquire.HTTPSpooler:Starting spooling: Bergamot/2020_11_3/EMC0406S1/try2/000/A1.pcs

'http://10.150.7.3:15348/Bergamot/2020_11_3/EMC0406S1/try2/000/A1.pcs/metadata.json'
DEBUG:PYME.Acquire.Utils.pointScanner:Current positions: {'x': 0.0, 'x_target': 0.0, 'y': -346.0, 'y_target': -346.0, 'z': 49.986000000000075, 'z_target': 50.0}

-7 7 -1
(1604439810, 362011) 6 0
Traceback (most recent call last):
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 227, in onExpReady
    d = self.getFrame()
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 198, in getFrame
    self.cam.ExtractColor(cs,0)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Hardware\Camera.py", line 1039, in ExtractColor
    self.camera_class.ExtractColor(self, self.chip_data, mode)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Hardware\HamamatsuDCAM\HamamatsuORCA.py", line 300, in ExtractColor
    raise DCAMZeroBufferedException()
PYME.Acquire.Hardware.HamamatsuDCAM.HamamatsuORCA.DCAMZeroBufferedException
DEBUG:PYME.Acquire.frameWrangler:retrying software trigger

Exception in thread Thread-34:
Traceback (most recent call last):
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 227, in onExpReady
    d = self.getFrame()
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 198, in getFrame
    self.cam.ExtractColor(cs,0)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Hardware\Camera.py", line 1039, in ExtractColor
    self.camera_class.ExtractColor(self, self.chip_data, mode)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Hardware\HamamatsuDCAM\HamamatsuORCA.py", line 300, in ExtractColor
    raise DCAMZeroBufferedException()
PYME.Acquire.Hardware.HamamatsuDCAM.HamamatsuORCA.DCAMZeroBufferedException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 295, in _poll_loop
    self.onExpReady()
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\frameWrangler.py", line 248, in onExpReady
    self.cam.FireSoftwareTrigger()
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Hardware\HamamatsuDCAM\HamamatsuORCA.py", line 190, in FireSoftwareTrigger
    self.checkStatus(dcam.dcamcap_firetrigger(self.handle, 0), 'dcamcap_firetrigger')
  File "c:\users\bergamot\code\python-microscopy\PYME\Acquire\Hardware\HamamatsuDCAM\HamamatsuDCAM.py", line 500, in checkStatus
    self.getCamInfo(fn_return))
PYME.Acquire.Hardware.HamamatsuDCAM.HamamatsuDCAM.DCAMException: DCAM error for dcamcap_firetrigger with return value -2147483385: Status is not busy!

Warning: not keeping up with camera, giving up with 1 frames still in buffer
n live: 0
n live: 0
```

**Comment by barentine** [comment]
I'm going to close this, as it is no longer a functional issue. Though it is a bit unsightly I will close this ticket and can always reference it later/re-open if we do something about it
