### ISSUE TITLE
Make PYME work with wx > 3

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#52]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/52) by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

PYME needs wxPython 3 (conda install wxpython=3) to work currently.

Needs more testing to establish if there are any remaining roadblocks to wx=4.x

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

This is not strictly true, although we do currently pin to wx < 3.9 in the recipes for the conda packages. We might need to rebuild the pyme-depends package to make sure that this is reflected in the current built package.

That said, most things should work on wx=4.x, and everything should work on wx=2.x. If we are going with wx=3.x, we want at least 3.0.2.0 (not 3.0).

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Are there any specific errors that you have found with wx=4?

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

wx=4.x compatibility changes were in commit 248be5f

there are still quite a few warnings, but

- you might need a really recent version of traisui
- dh5view should run 
- VisGUI mostly runs, unless you have to call CreateFoldPanel() after the initial creation which fails when destroying the traits views

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

I tried opening and h5r file in VisGUI. I received the following error.


```
#!python

Pipeline Created
DEBUG:PYME.LMVis.VisGUI:Creating tabs
0
DEBUG:PYME.LMVis.VisGUI:Finished creating tabs
c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py:99: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(sys.maxsize, key)
Traceback (most recent call last):
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\visCore.py", line 377, in OnOpenFile
    self.OpenFile(filename)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\visCore.py", line 677, in OpenFile
    self.CreateFoldPanel()
  File "c:\users\zrc4\documents\python-microscopy\PYME\ui\AUIFrame.py", line 119, in CreateFoldPanel
    genFcn(self.sidePanel)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\visCore.py", line 144, in GenPanels
    self.filterPane = CreateFilterPane(sidePanel, self.pipeline.filterKeys, self.pipeline, self)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py", line 33, in CreateFilterPane
    pane = FilterPane(panel, mapping, pipeline, visFr)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py", line 240, in __init__
    self.pFilter = FilterPanel(self, filterKeys, pipeline.selectedDataSource)
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py", line 67, in __init__
    self.populate()
  File "c:\users\zrc4\documents\python-microscopy\PYME\LMVis\filterPane.py", line 99, in populate
    ind = self.lFiltKeys.InsertStringItem(sys.maxsize, key)
  File "C:\Users\zrc4\AppData\Local\conda\conda\envs\pyme_test\lib\site-packages\wx\core.py", line 82, in deprecated_func
    return item(*args)
wx._core.wxAssertionError: C++ assertion "rv != -1" failed at ..\..\src\msw\listctrl.cpp(1730) in wxListCtrl::InsertItem(): failed to insert an item in wxListCtrl
```

This error can be fixed by running conda install wxpython=3.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

This looks like it might be related to issue #51. Does the workaround for #51 (commit ba0780c) fix this too?

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

I've changed this to an enhancement. We currently pin to wx < 3.9, which means that this is no longer a bug.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Note that the standard pyme conda package with wxpython 3.0.0 and numpy 1.11 on linux does not have a particularly functional VisGUI. The panels on the left don’t work with the exception of the output selection drop-down.

![](https://bitbucket.org/repo/kAoqj6/images/1881088106-image.png)
edit: note that wxpython=3.0.2.0 does no better

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

What versions of linux, traits, and traitsui?

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

ubuntu 16.04

traits                    5.1.1            py27h7b6447c\_0   traitsui                  6.1.1                      py\_0

**Comment by David-Baddeley** [comment]
Closing the python 3 super issue as we're close enough that we should now raise specific issues for any remaining python 3 issues.
