### ISSUE TITLE
DataExporter wraps when saving as legacy tiff

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#54]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/54) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Not immediately clear where/why this is happening, but "save as" or export data starting at 0 generates a tif which appears to put the [-1] frame in the [0] spot, the [0] frame in the [1] spot. In the exported stack the last frame is skipped when "playing" the series. However, if you look at image.data.getSlice(last_valid_index), this returns the same image for the exported and original ImageStacks, and image.data.shape is the same. For some reason it is getting wrapped funny.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Does this also happen when saving as .h5?

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Good hunch - the behavior I'm getting with h5 exports is fine.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

This is again odd. Finally got round to trying this, but I can't replicate on OSX. What is the dimensionality, source, and data type of the image (is it colour?)

Simple testing code to generate a traceable image below:

```
#!python
from PYME.DSView import View3D, ViewIm3D
d = np.zeros([50,50,5])
for i in range(5):
    d[:,:,i] = i
    
View3D(d)

```

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

```
#!python

~/code/python-microscopy$ python
Python 2.7.14 |Anaconda custom (64-bit)| (default, Oct 16 2017, 17:29:19) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from PYME.DSView import View3D, ViewIm3D
>>> d = np.zeros([50, 50, 5])
>>> for i in range(5):
...     d[:,:,i] = i
... 
>>> View3D(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PYME/DSView/dsviewer.py", line 472, in View3D
    parent=parent, glCanvas=glCanvas)
  File "PYME/DSView/dsviewer.py", line 75, in __init__
    AUIFrame.__init__(self,parent, -1, title,size=size, pos=wx.DefaultPosition)
  File "PYME/ui/AUIFrame.py", line 11, in __init__
    wx.Frame.__init__(self, *args, **kwargs)
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_windows.py", line 580, in __init__
    _windows_.Frame_swiginit(self,_windows_.new_Frame(*args, **kwargs))
wx._core.PyNoAppError: The wx.App object must be created first!

```

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Hmm, I may have mispoke when I said tif, as I think I was probably saving to tiff. At the moment, I get the following error when I try tiff though, so I'll wade through that before I check again:

```
#!python

Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/DSView/dsviewer.py", line 317, in OnExport
    self.image.Save(crop = True, view = self.view)
  File "/home/smeagol/code/python-microscopy/PYME/IO/image.py", line 999, in Save
    dataExporter.CropExportData(view, self.mdh, self.events, self.seriesName)
  File "/home/smeagol/code/python-microscopy/PYME/IO/dataExporter.py", line 538, in CropExportData
    exp.Export(ds, filename, dlg.GetXSlice(), dlg.GetYSlice(), dlg.GetZSlice(),mdh, events, origName)
  File "/home/smeagol/code/python-microscopy/PYME/IO/dataExporter.py", line 192, in Export
    saveTiffStack.saveTiffMultipage(data[xslice, yslice, zslice], outFile)
  File "/home/smeagol/code/python-microscopy/PYME/IO/FileUtils/saveTiffStack.py", line 86, in saveTiffMultipage
    ifdLength = ii._debug_multipage.i16(fp.read(2))
AttributeError: 'ImageFileDirectory_v2' object has no attribute 'i16'

```

The data saves correctly when I save to ome tif and the dimensionality is 
image.data.shape
[960, 240, 24, 1]

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

You can avoid the wx.App error above by either running from the dh5view shell (e.g. after having launched in test mode - `dh5view -t`), or by running under `ipython --pylab=wx` or `ipython --gui='wx'` (you might need to do at least one plot command before it will work if you go the `--pylab=wx` route). 

.tiff  (as opposed to OME tif) saving should really be deprecated unless you can think of a use case where we need it.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

changed priority as we should probably just do away with the legacy .tiff support (at least when saving)

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Legacy tiff export removed from GUI. That should wrap this up.
