### ISSUE TITLE
More flexible traits.CStr handling in recipe modules

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#57]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/57) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Might be nice to strip 'quotes' from CStr types rather than ending up with strings that include the ' ' if someone is trying to get the data type right.

Example from

```
#!python

- localisations.DensityMapping:
    MCProbability: 1.0
    colours:
    - Chan0
    inputLocalizations: localizations
    jitterScale: 2.0
    jitterScaleZ: 75.0
    jitterVariable: neighborDistances
    jitterVariableZ: '1.0'
    numSamples: 10
    outputImage: tri
    pixelSize: 40.0
    renderingModule: 3D Triangularisation
    softRender: true
    zBounds:
    - -500.0
    - 500.0
    zBoundsMode: min-max
    zSliceThickness: 100.0
```

The following print statements:

```
#!python

    def _genJitVals(self, jitParamName, jitScale):
        print(jitParamName)
        print(type(jitParamName))
        print('neighbourDistances')
        print(jitParamName == 'neighbourDistances')
        print(type(jitParamName) == type('neighbourDistances'))
        print('--------------------------------')
        if jitParamName == '1.0':
            jitVals = np.ones(self.colourFilter['x'].shape)
        elif jitParamName in self.colourFilter.keys():
            jitVals = self.colourFilter[jitParamName]
        elif jitParamName == 'neighbourDistances':
            jitVals = self._get_neighbour_dists()
        elif jitParamName == 'neighbourErrorMin':
            jitVals = np.minimum(self.colourFilter['error_x'], self._get_neighbour_dists())
        elif jitParamName in self.genMeas:
            jitVals = self.pipeline.GeneratedMeasures[jitParamName]

        return jitVals*jitScale
```

```
#!python

'neighbourDistances'
<type 'str'>
neighbourDistances
False
True
--------------------------------
ERROR:PYME.recipes.base:Error in recipe module: <PYME.recipes.localisations.DensityMapping object at 0x7f7d9aa52d70>
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 335, in execute
    m.execute(self.namespace)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/localisations.py", line 93, in execute
    namespace[self.outputImage] = renderer.Generate(self.get())
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 248, in Generate
    ims.append(np.atleast_3d(self.genIm(settings, imb, mdh)))
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 465, in genIm
    jitVals = np.maximum(self._genJitVals(jitParamName, jitScale), pixelSize)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 153, in _genJitVals
    elif jitParamName in self.genMeas:
AttributeError: Triangle3DRenderer instance has no attribute 'genMeas'
ERROR:PYME.recipes.runRecipe:Error running recipe
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/runRecipe.py", line 89, in runRecipe
    res = recipe.execute()
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 335, in execute
    m.execute(self.namespace)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/localisations.py", line 93, in execute
    namespace[self.outputImage] = renderer.Generate(self.get())
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 248, in Generate
    ims.append(np.atleast_3d(self.genIm(settings, imb, mdh)))
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 465, in genIm
    jitVals = np.maximum(self._genJitVals(jitParamName, jitScale), pixelSize)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 153, in _genJitVals
    elif jitParamName in self.genMeas:
AttributeError: Triangle3DRenderer instance has no attribute 'genMeas'
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/batchProcess.py", line 30, in runRec
    runRecipe.runRecipe(*args)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/runRecipe.py", line 89, in runRecipe
    res = recipe.execute()
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 335, in execute
    m.execute(self.namespace)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/localisations.py", line 93, in execute
    namespace[self.outputImage] = renderer.Generate(self.get())
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 248, in Generate
    ims.append(np.atleast_3d(self.genIm(settings, imb, mdh)))
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 465, in genIm
    jitVals = np.maximum(self._genJitVals(jitParamName, jitScale), pixelSize)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 153, in _genJitVals
    elif jitParamName in self.genMeas:
AttributeError: Triangle3DRenderer instance has no attribute 'genMeas'


```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Is this going to be specific to jitterVariable? An alternative approach would be to replace the special '1.0' string with something that doesn't need to be escaped.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

The yaml parser already does this where appropriate. Your error is a typo in neighbour (which should use UK/ international English spelling).

```
#!python

yaml.load("a: foo")
>>>{'a': 'foo'}

yaml.load("a: 'foo'")
>>>{'a': 'foo'}

print(yaml.load("a: 'foo'")['a'])
>>>foo

```

Your print statements just show the difference between `str(X)` and `repr(X)`.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Should have been invalid rather than closed.
