### ISSUE TITLE
Cannot import delaunay from matplotlib

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#59]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/59) by Adrien (Bitbucket: [AdrienM8](https://bitbucket.org/AdrienM8), ).**

----------------------------------------

Greetings,

First of all my issue looks pretty much like [this one](https://bitbucket.org/david_baddeley/python-microscopy/issues/4/numpy-version-error-prevents-pyme-from) except with matplotlib.

I installed Anaconda from scratch, then ran 

```
#!python

conda config --add channels david_baddeley
conda install python-microscopy
```

then when running any of the three:

```
#!python

dh5view -t -m lite
PYMEAcquire
VisGUI
```

I get the following error:

```
#!python

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\VisGUI-script.py", line 3, in <module>
    import PYME.Analysis.LMVis.VisGUI
  File "C:\ProgramData\Anaconda2\lib\site-packages\PYME\Analysis\LMVis\VisGUI.py", line 30, in <module>
    from PYME.DSView.dsviewer_npy_nb import View3D
  File "C:\ProgramData\Anaconda2\lib\site-packages\PYME\DSView\__init__.py", line 23, in <module>
    from dsviewer_npy_nb import View3D, ViewIm3D
  File "C:\ProgramData\Anaconda2\lib\site-packages\PYME\DSView\dsviewer_npy_nb.py", line 47, in <module>
    from PYME.DSView.image import ImageStack
  File "C:\ProgramData\Anaconda2\lib\site-packages\PYME\DSView\image.py", line 42, in <module>
    from PYME.Analysis.LMVis.visHelpers import ImageBounds
  File "C:\ProgramData\Anaconda2\lib\site-packages\PYME\Analysis\LMVis\visHelpers.py", line 32, in <module>
    from matplotlib import delaunay
ImportError: cannot import name delaunay
```

my matplotlib version is 2.1.0
I tried running *conda update conda* and* conda create -n PYME -c david_baddeley python-microscopy* but issue remained.

Do you know any way around ? Is there a specific matplotlib version to use?
I'm running Python 2.7.15 on Anaconda, Windows 7, 64bits. Provided conda list for more information.
Many thanks for your help, and for PYME

Adrien

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Hi @AdrienM8 , delaunay was depreciated from matplotlib in 1.4, and got dropped somewhere between version 2.0.2 and version 2.1.0.

We've updated our calls to matplotlib.tri, but for some reason your installation defaulted to a version of PYME which is about 2.5 years old. Can you try running
```
#!bash

conda update python-microscopy
```
or if that doesn't work due to conflicts, be more forceful with
```
#!bash

conda install python-microscopy=18.07.17
```
to see if you have problems with the most recent conda build for windows?

Thanks,
andrew

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Just a quick note on this - pulling old versions of PYME is usually due to problems satisfying dependencies in an existing anaconda installation, meaning that `conda update python-microscopy` might not get you anywhere.

The installation instructions assume a clean install - If you use the anaconda for other stuff, it might be worth creating a dedicated conda environment to run PYME in (e.g. `conda create -n PYME python=2.7` see https://conda.io/docs/user-guide/tasks/manage-environments.html)

**Comment by David-Baddeley** [comment]
**Original comment by Adrien (Bitbucket: [AdrienM8](https://bitbucket.org/AdrienM8), ).**

----------------------------------------

Alright, thanks you all for your quick and precise answers !

```
#!python

conda update python-microscopy
```
Did the job :) After this I also had to reinstall numpy and now all three commands work fine. Btw I will only use Anaconda for pyme.

The issue may have risen from the fact that I installed and uninstalled Anaconda for Python 3 some times ago, and still have Spyder with python 3 on my computer. But i'm not sure about it.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Glad to hear it worked, @AdrienM8

@david_baddeley , can you mark this as resolved?
