### ISSUE TITLE
DisplayObject selection begin and end aren't necessarily sorted

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#63]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/63) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Can result in failed crops because it tries to index begin:end, which only works in end > begin

```
#!python

Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/DSView/modules/cropping.py", line 71, in OnCrop
    dv = ViewIm3D(im, mode=mode, glCanvas=self.dsviewer.glCanvas, parent=wx.GetTopLevelParent(self.dsviewer))
  File "/home/smeagol/code/python-microscopy/PYME/DSView/dsviewer.py", line 487, in ViewIm3D
    
  File "/home/smeagol/code/python-microscopy/PYME/DSView/dsviewer.py", line 106, in __init__
    self.do.Optimise()
  File "/home/smeagol/code/python-microscopy/PYME/DSView/displayOptions.py", line 316, in Optimise
    self.OnChange()
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

```
Fixed in PR #189

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Fixed in commit 4204 ?? \(at least the cropping specific case\). I suspect this was duplicated somewhere else - decision was that selection remains unsorted, but `sorted_selection` attribute added for cases that need a sorted selection.
