### ISSUE TITLE
have triangulation and gaussian (2d) renderers generate same sized images

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#65]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/65) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

currently one cannot (generally) combined differently rendered images, e.g. with the following recipe:

```
#!yaml

- localisations.AddPipelineDerivedVars:
    inputDriftResults: ''
    inputEvents: ''
    inputFitResults: fitResults
    outputLocalizations: pipeline
    pixelSizeNM: 1.0
- localisations.DensityMapping:
    MCProbability: 1.0
    colours:
    - chan0
    - chan1
    inputLocalizations: localizations
    jitterScale: 1.0
    jitterScaleZ: 1.0
    jitterVariable: neighbourDistances
    jitterVariableZ: neighbourDistances
    numSamples: 10
    outputImage: tri
    pixelSize: 40.0
    renderingModule: Jittered Triangulation
    softRender: true
    zBounds:
    - -500.0
    - 500.0
    zBoundsMode: min-max
    zSliceThickness: 40.0
- base.JoinChannels:
    inputChan0: tri_0
    inputChan1: gauss_1
    inputChan2: ''
    inputChan3: ''
    outputName: rendered
- output.RGBImageOutput:
    filePattern: '{output_dir}/{file_stub}_rendered.png'
    inputName: rendered
    scaling: percentile
    scaling_factor: 0.99999
    scheme: File
    zoom: 1
- localisations.ProcessColour:
    input: pipeline
    output: localizations
- localisations.DensityMapping:
    MCProbability: 1.0
    colours:
    - chan0
    - chan1
    inputLocalizations: localizations
    jitterScale: 1.0
    jitterScaleZ: 1.0
    jitterVariable: '1.0'
    jitterVariableZ: '1.0'
    numSamples: 10
    outputImage: gauss
    pixelSize: 40.0
    renderingModule: Gaussian
    softRender: true
    zBounds:
    - -500.0
    - 500.0
    zBoundsMode: manual
    zSliceThickness: 40.0
- base.ExtractChannel:
    channelToExtract: 1
    inputName: gauss
    outputName: gauss_1
- base.ExtractChannel:
    channelToExtract: 0
    inputName: tri
    outputName: tri_0

```

as you get the following traceback (modulo whatever your sizes are):

```
#!python

Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/batchProcess.py", line 30, in runRec
    runRecipe.runRecipe(*args)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/runRecipe.py", line 96, in runRecipe
    recipe.save(context)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 501, in save
    mod.save(self.namespace, context)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/output.py", line 290, in save
    v = self.generate(namespace)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/output.py", line 259, in generate
    data[:,:,i] = chan_i
ValueError: could not broadcast input array from shape (695,637) into shape (694,636)


```

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Effectively added in commit 0bb3c79 by setting manual / inherited image bounds
