### ISSUE TITLE
can overflow hdf I/O for fast-executing recipes

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#66]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/66) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

When batch processing on many files with fast recipes, can end up opening hdf files faster than we close them (with our ~10 second timeout). 

Possible solutions include handling the following exception with a pause/retry, which would be preferable to the look-before-you-leap approach of checking number of open hdf files and potentially pausing before opening another.

```
#!python

Unable to open/create file '/media/smeagol/SSD/censored.h5r'
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/recipes/batchProcess.py", line 30, in runRec
  File "/home/smeagol/code/python-microscopy/PYME/recipes/runRecipe.py", line 86, in runRecipe
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 553, in loadInput
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/tables/file.py", line 320, in open_file
  File "/home/smeagol/anaconda2/lib/python2.7/site-packages/tables/file.py", line 784, in __init__
  File "tables/hdf5extension.pyx", line 487, in tables.hdf5extension.File._g_new
HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 586, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1236, in H5F_open
    unable to open file: time = Tue Jan  8 20:48:03 2019
, name = '/media/smeagol/SSD/censored.h5r', tent_flags = 0
  File "H5FD.c", line 809, in H5FD_open
    open failed
  File "H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = '/media/smeagol/SSD/censored.h5r', errno = 24, error message = 'Too many open files', flags = 0, o_flags = 0

End of HDF5 error back trace

```

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Fixed in PR #211. I wasn't running into a problem with opening hdf's faster than they were being closed (adding retries on opens with delays never helped), but rather we hadn't wrapped the recipe file open such that it'd be automatically closed after the keep-alive timeout if it wasn't still in use.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

PR #211 does not fix this but instead introduces additional race conditions - it's just luck that it worked, but in recipe processing takes longer than 10s per input file it will break things badly.

Try changes in commit #4307

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

i.e. commit 4307 should now have fixed it by making sure that the hdf file gets closed in the load_inputs method.
