### ISSUE TITLE
Cairo requirement should be added to pyme-depends for Python 3

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#70]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/70) by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

If you run conda install pyme-depends on a fresh Anaconda python 3 environment, you need to install cairo as well. Should just add this as part of pyme-depends dependencies. In the meantime, conda install pycairo fixes this.

Traceback (most recent call last):
  File "/anaconda2/envs/pyme3/bin/visgui", line 11, in <module>
    load_entry_point('PYME', 'console_scripts', 'VisGUI')()
  File "/anaconda2/envs/pyme3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/anaconda2/envs/pyme3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/anaconda2/envs/pyme3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/anaconda2/envs/pyme3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/zachcm/Documents/python3-triangles/PYME/LMVis/VisGUI.py", line 58, in <module>
    from PYME.recipes import recipeGui
  File "/Users/zachcm/Documents/python3-triangles/PYME/recipes/recipeGui.py", line 23, in <module>
    from PYME.recipes import batchProcess
  File "/Users/zachcm/Documents/python3-triangles/PYME/recipes/batchProcess.py", line 9, in <module>
    matplotlib.use('Cairo', warn=False)
  File "/anaconda2/envs/pyme3/lib/python3.6/site-packages/matplotlib/__init__.py", line 1391, in use
    switch_backend(name)
  File "/anaconda2/envs/pyme3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/anaconda2/envs/pyme3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/anaconda2/envs/pyme3/lib/python3.6/site-packages/matplotlib/backends/backend_cairo.py", line 24, in <module>
    raise ImportError("cairo backend requires that cairocffi or pycairo "
ImportError: cairo backend requires that cairocffi or pycairo is installed

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

This might also be needed on Python 2. Easy fix in any case.

At some point we need to make a decision on what are core dependencies, and what are optional (I'm not sure that cairo is actually being used in the recipe code - at least not for much - idea is an offscreen renderer for matplotlib figures, but there is little in the way of infrastructure for figure generation in recipes at present. Might be used in the particle tracking module.)

**Comment by David-Baddeley** [comment]
**Original comment by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

I don't think cairo should be necessary, but visgui won't launch without it as of right now.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Commit #4417 should make this a run-time dependency of batchProcess (when run as a script). Hopefully this is enough to resolve this.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Partial fix by making cairo a run-time dependency, modulo getting recipe plotting architecture finalized

**Comment by zacsimile** [comment]
Haven't run into this in a long time. I think it's fixed. Can close.

**Comment by David-Baddeley** [comment]
It's still only a partial fix - i.e. commit #4417 made it so you don't run into it all the time, but you still will if you try and generate offline plotting in recipes.
