### ISSUE TITLE
[BUG] way we use unifiedIO.local_or_temp_filename issue on Windows 10? PYMEVis cluster h5r loading

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#702]
**Describe the bug**
```
(chaos) C:\Users\Bergamot>PYMEVis pyme-cluster:///Bergamot/2020_12_9/GB_STORM_Slide2/try2/000/analysis/9_12_series_BA.h5r
c:\Users\Bergamot\Anaconda2\envs\chaos\lib\_collections_abc.py:702: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  return len(self._mapping)
c:\Users\Bergamot\Anaconda2\envs\chaos\lib\_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping
c:\users\bergamot\code\python-microscopy\PYME\misc\extraCMaps.py:73: MatplotlibDeprecationWarning:
The revcmap function was deprecated in Matplotlib 3.2 and will be removed two minor releases later. Use Colormap.reversed() instead.
  cmapdat_r = cm.revcmap(ndat[cmapname])
Trying to load 3rd party recipe module pyme_omero.recipe_modules.omero_upload
Loaded 3rd party recipe module pyme_omero.recipe_modules.omero_upload
Trying to load 3rd party recipe module pyme_rcnn.recipe_modules.rcnn_segment
Loaded 3rd party recipe module pyme_rcnn.recipe_modules.rcnn_segment
INFO:OpenGL.acceleratesupport:No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
INFO:OpenGL.GLUT.special:Using NT-specific GLUT calls with exit callbacks
quaternion module not found, disabling custom clip plane orientations
quaternion module not found, disabling custom clip plane orientations
New Canvas
DEBUG:PYME.LMVis.visCore:Creating VisGUI menu bar
DEBUG:PYME.LMVis.Extras:Initializing QPobjectSegment plugin
DEBUG:PYME.LMVis.Extras:Initializing animation plugin
DEBUG:PYME.LMVis.Extras:Initializing clusterAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing dockedPanel plugin
DEBUG:PYME.LMVis.Extras:Initializing extra_layers plugin
DEBUG:PYME.LMVis.Extras:Initializing fiducial plugin
DEBUG:PYME.LMVis.Extras:Initializing flagZMotionArtifacts plugin
DEBUG:root:Adding menu items for event filters
DEBUG:PYME.LMVis.Extras:Initializing fusionUtils plugin
DEBUG:PYME.LMVis.Extras:Initializing multiColourAnalysis plugin
DEBUG:PYME.LMVis.Extras:Initializing multiviewMapping plugin
DEBUG:root:Adding menu items for multi-view manipulation
DEBUG:PYME.LMVis.Extras:Initializing objectMeasurements plugin
DEBUG:PYME.LMVis.Extras:Initializing particleTracking plugin
DEBUG:PYME.LMVis.Extras:Initializing perFrameVariable plugin
DEBUG:PYME.LMVis.Extras:Initializing photophysics plugin
DEBUG:PYME.LMVis.Extras:Initializing pointSetGeneration plugin
DEBUG:PYME.LMVis.Extras:Initializing pointwiseColoc plugin
DEBUG:PYME.LMVis.Extras:Initializing saved_views plugin
Saved Views are deprecated -  use the ones with animation instead and remove me!
DEBUG:PYME.LMVis.Extras:Initializing scaleBox plugin
DEBUG:PYME.LMVis.Extras:Initializing sequentialSpecies plugin
DEBUG:PYME.LMVis.Extras:Initializing setBGImage plugin
DEBUG:PYME.LMVis.Extras:Initializing shiftmapGenerator plugin
DEBUG:PYME.LMVis.Extras:Initializing showShortcuts plugin
DEBUG:PYME.LMVis.Extras:Initializing snapshot plugin
DEBUG:PYME.LMVis.Extras:Initializing spherical_harmonics plugin
DEBUG:root:Adding menu items for spherical harmonic (shell) fitting
DEBUG:PYME.LMVis.Extras:Initializing subsets plugin
DEBUG:PYME.LMVis.Extras:Initializing surface_fitting plugin
DEBUG:PYME.LMVis.Extras:Initializing temperaturePlot plugin
DEBUG:PYME.LMVis.Extras:Initializing vibration plugin
ERROR:PYME.LMVis.Extras:Error loading plugin: #package_name.visgui_modules.NAME_OF_FILE_WITHOUT_EXTENSION
Traceback (most recent call last):
  File "c:\users\bergamot\code\python-microscopy\PYME\LMVis\Extras\__init__.py", line 46, in InitPlugins
    m = __import__(mn, fromlist=mn.split('.')[:-1])
ModuleNotFoundError: No module named '#package_name'
DEBUG:root:Adding menu items for OMERO loading
Creating fold panel
GenPanels
Creating datasource panel
RecipeView._layout
Input datasources:  []
c:\users\bergamot\code\python-microscopy\PYME\LMVis\filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
c:\users\bergamot\code\python-microscopy\PYME\LMVis\filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
c:\users\bergamot\code\python-microscopy\PYME\LMVis\filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
Image list size: 1
Creating layers GUI
height:  0
NB best size: wx.Size(200, 0)
RecipeView._layout
Input datasources:  []
c:\users\bergamot\code\python-microscopy\PYME\LMVis\filterPane.py:111: wxPyDeprecationWarning: Call to deprecated item. Use InsertItem instead.
  ind = self.lFiltKeys.InsertStringItem(ind+1, key)
c:\users\bergamot\code\python-microscopy\PYME\LMVis\filterPane.py:112: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 1, '%3.2f' % value[0])
c:\users\bergamot\code\python-microscopy\PYME\LMVis\filterPane.py:113: wxPyDeprecationWarning: Call to deprecated item. Use SetItem instead.
  self.lFiltKeys.SetStringItem(ind, 2, '%3.2f' % value[1])
RecipeView._layout
Input datasources:  []
0
OpenGL - Version: b'4.6.0 NVIDIA 441.22'
Shader - Version: b'4.60 NVIDIA'
GL_MAX_SAMPLES: 32, GL_SAMPLES: 4
DEBUG:PYME.LMVis.shader_programs.ShaderProgramFactory:New shader program created: <class 'PYME.LMVis.shader_programs.DefaultShaderProgram.DefaultShaderProgram'>
c:\users\bergamot\code\python-microscopy\PYME\ui\manualFoldPanel.py:37: wxPyDeprecationWarning: Using deprecated class. Use Colour instead.
  col = wx.NamedColour(col)
Ev Idle
('points', 't')
refreshed
Creating Pipeline
Traceback (most recent call last):
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\site-packages\wx\core.py", line 2228, in Notify
    self.notify()
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\site-packages\wx\core.py", line 3384, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "c:\users\bergamot\code\python-microscopy\PYME\LMVis\visCore.py", line 750, in OpenFile
    self.pipeline.OpenFile(filename, **args)
  File "c:\users\bergamot\code\python-microscopy\PYME\LMVis\pipeline.py", line 787, in OpenFile
    ds = self._ds_from_file(fn, **kwargs)
  File "c:\users\bergamot\code\python-microscopy\PYME\LMVis\pipeline.py", line 650, in _ds_from_file
    h5f = tables.open_file(filename)
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\site-packages\tables\file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\site-packages\tables\file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "C:\ci\hdf5_1545244154871\work\src\H5F.c", line 509, in H5Fopen
    unable to open file
  File "C:\ci\hdf5_1545244154871\work\src\H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "C:\ci\hdf5_1545244154871\work\src\H5Fint.c", line 1546, in H5F_open
    unable to open file: time = Fri Dec 11 10:01:21 2020
, name = 'C:\Users\Bergamot\AppData\Local\Temp\tmp3pqscmta.h5r', tent_flags = 0
  File "C:\ci\hdf5_1545244154871\work\src\H5FD.c", line 734, in H5FD_open
    open failed
  File "C:\ci\hdf5_1545244154871\work\src\H5FDsec2.c", line 346, in H5FD_sec2_open
    unable to open file: name = 'C:\Users\Bergamot\AppData\Local\Temp\tmp3pqscmta.h5r', errno = 13, error message = 'Permission denied', flags = 0, o_flags = 0

End of HDF5 error back trace

Unable to open/create file 'C:\Users\Bergamot\AppData\Local\Temp\tmp3pqscmta.h5r'
```

**To Reproduce**
1. on a cluster-connected win10 machine, try to open an h5r file direct from PYMEVis

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: [e.g. Win10] win10
 - Python version: 3.7
 - numpy version: 1.19.2
 - wxpython version [if a UI bug]: 4.0.4

**Additional context**
looks like while unix lets you open/reopen temp files that may not always be the case on windows?

**Comment by barentine** [comment]
really anytime you use unifiedIO.local_or_temp_filename on win10 it fails
```
Traceback (most recent call last):
  File "c:\users\bergamot\code\python-microscopy\PYME\cluster\taskWorkerHTTP.py", line 341, in computeLoop
    recipe.execute()
  File "c:\users\bergamot\code\python-microscopy\PYME\recipes\base.py", line 718, in execute
    m.execute(self.namespace)
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\site-packages\torch\autograd\grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "c:\users\bergamot\code\pyme-automateroi\autoroi\recipe_modules\mrcnn_segment.py", line 132, in execute
    model, device = prep_model(self.model, self.device)
  File "c:\users\bergamot\code\pyme-automateroi\autoroi\recipe_modules\mrcnn_segment.py", line 31, in prep_model
    model.load_state_dict(torch.load(f))
  File "c:\Users\Bergamot\Anaconda2\envs\chaos\lib\site-packages\torch\serialization.py", line 381, in load
    f = open(f, 'rb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Bergamot\\AppData\\Local\\Temp\\tmpgz1ip0d6.pt'
```

**Comment by barentine** [comment]
from the docs on namedtemporaryfiles

> This function operates exactly as TemporaryFile() does, except that the file is guaranteed to have a visible name in the file system (on Unix, the directory entry is not unlinked). That name can be retrieved from the name attribute of the returned file-like object. Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).
