### ISSUE TITLE
Overzealous import of mayavi in spherical_harmonics.py

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#71]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/71) by Zach Connerty-Marin (Bitbucket: [zacsimile](https://bitbucket.org/zacsimile), GitHub: [zacsimile](https://github.com/zacsimile)).**

----------------------------------------

Conda install mayavi downgrades python 3 to python 2. Cannot launch visgui in python 3 as a result.

Traceback (most recent call last):
  File "/Users/zachcm/Documents/python3-triangles/PYME/LMVis/VisGUI.py", line 421, in OnInit
    self.main = VisGUIFrame(None, self.filename, use_shaders=self.use_shaders, cmd_args=self.cmd_args)
  File "/Users/zachcm/Documents/python3-triangles/PYME/LMVis/VisGUI.py", line 90, in __init__
    self.CreateMenuBar(use_shaders=use_shaders)
  File "/Users/zachcm/Documents/python3-triangles/PYME/LMVis/visCore.py", line 293, in CreateMenuBar
    Extras.InitPlugins(self)
  File "/Users/zachcm/Documents/python3-triangles/PYME/LMVis/Extras/__init__.py", line 40, in InitPlugins
    m = __import__('PYME.LMVis.Extras.' + mn, fromlist=['PYME', 'LMVis', 'Extras'])
  File "/Users/zachcm/Documents/python3-triangles/PYME/LMVis/Extras/spherical_harmonics.py", line 4, in <module>
    from mayavi import mlab
ModuleNotFoundError: No module named 'mayavi'
OnInit returned false, exiting...
Error in atexit._run_exitfuncs:
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at /opt/concourse/worker/volumes/live/b30868b5-2a7c-479c-4e29-27874bbc69a6/volume/wxpython_1547931175613/work/ext/wxWidgets/src/common/wincmn.cpp(478) in ~wxWindowBase(): any pushed event handlers must have been removed

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Mayavi is a problematic beast & generally a dependency nightmare (it's what keeps us stuck at numpy 1.11). It should probably be a 'soft dependency' - i.e. everything should launch and run even when absent and just the code that explicitly depends on mayavi should break (As far as I know this 

Best solution (and the one employed in other places where mayavi is imported - e.g. the vis3d module in dh5view) is to defer mayavi loading until the last possible moment (i.e. right before you need it). I'm going to call this Andrew's bug, but would recommend the following:

* Refactor the display code into it's own function call
* Put `from mayavi import mlab` as the first line of this function (i.e. the import will fail when you try and display the shell, not when you load visgui)
* [optional] wrap the display function up in a try ... catch statement so that the shell fitting still works when Mayavi is not there.

The long term solution would be to create a triangular mesh for the harmonic shell and display it right in VisGUI.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

We could also try and fix mayavi, but that would be a LOT of work!

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Have committed a very quick partial fix (moved the import statement into the function call) that allows VisGUI to load, but leaves the spherical harmonic module broken.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

should be fixed in a safe way in commit 4900
