### ISSUE TITLE
Make quadtree rendering work from recipes

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#72]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/72) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

```
#!python

Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 304, in GenerateGUI
    im = self.Generate(dlg.get_settings())
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 269, in Generate
    ims.append(np.atleast_3d(self.genIm(settings, imb, mdh)))
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/renderers.py", line 508, in genIm
    if not np.mod(np.log2(pixelSize/self.visFr.QTGoalPixelSize), 1) == 0:#recalculate QuadTree to get right pixel size
AttributeError: 'VisGUIFrame' object has no attribute 'QTGoalPixelSize'

```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

The quad-tree rendering is broken on multiple levels.  Fixing it is waiting on a) time, and b) a number of design choices. Big questions to be answered are:

* Do we want to resurrect the live quad tree display (this is where QTGoalPixelSize was defined)?
* If so, should that be based on the old code, or implemented as a special case of the 3D octree code?
* Even if we do resurrect the live quad tree display, should the renderer track this, or would it make more sense to have it independent of the display code?
* Do we want to add support for a jittered QuadTree

I'm a little reluctant to just ditch the quad tree altogether as it did have the neat feature of being able to adaptively pick local pixel sizes to give a consistent SNR across the image (i.e. large pixels where there are few localisations, small pixels where the localisations are dense.

**Comment by zacsimile** [comment]
I think we fixed this specific error in #265. However, as @David-Baddeley mentioned there,

> Will merge, but ultimately we should fix this properly (as it stands, it won't work when called from a recipe).
> 
> Ultimately this would involve 1 or more of the following:
> 
> * moving the `pipeline.GenQuads()` logic into the renderer
> * moving the `pipeline.GenQuads()` logic to a function in `visHelpers`
> * adding a `QuadTree` recipe module with the `GenQuads()` logic and abusing the octree layer to display it (this might be a better option than moving `GenQuads()` to the renderer if we felt it was important to be able to display the quadtree in VisGUI.
> 
> Both of the first two do not pre-compute and cache the quadtree, but that might not matter for what is a pretty niche case.
