### ISSUE TITLE
[BUG] pipeline['t'] goes int -> float in Multiview.MergeClumps, breaks pyDeClump.findClumps

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#749]
**Describe the bug**
```
 Error whilst running Corrections>Multiview>Calibrate Shifts
==============================================
python-microscopy=20.12.10
python=3.6.9, platform=linux
numpy=1.16.5, wx=4.0.4 gtk2 (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/ui/progress.py", line 107, in func
    return fcn(*args, **kwargs)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/Extras/multiviewMapping.py", line 205, in OnCalibrateShifts
    sm = calibration_module.apply_simple(self.pipeline.selectedDataSource)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 206, in apply_simple
    return self.apply(*args, **kwargs)[next(iter(self.outputs))]
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 185, in apply
    self.execute(namespace)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/multiview.py", line 310, in execute
    pix_size_nm=inp.mdh.voxelsize_nm.x)
  File "/home/smeagol/code/python-microscopy/PYME/Analysis/points/multiview.py", line 284, in pair_molecules
    assigned = pyDeClump.findClumps(t_index.astype(np.int32), x, y, delta_x, n_frame_sep)
  File "/home/smeagol/code/python-microscopy/PYME/Analysis/points/DeClump/pyDeClump.py", line 110, in findClumps
    frameIndices = (nRes + 2)*np.ones(t.max() + nFrames + 1, 'int32')
  File "/home/smeagol/miniconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 223, in ones
    a = empty(shape, dtype, order)
TypeError: 'numpy.float64' object cannot be interpreted as an integer


```

**Comment by barentine** [comment]
For most use cases one probably doesn't need to merge clumps and then find them again. I was a bit turned around with the workflow there (was calibrating multiview registration but the calibration does the finding/merging for you). I'm going to go ahead and close since it's a bit confusing whether to know if we want to hard type it there, or throw the error, since in this case the error pointed out (eventually) that I was doing something weird
