### ISSUE TITLE
Lack of Camera.ADOffset breaks loading of series < 10 frames long

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#75]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/75) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Self explanatory. Not necessarily a problem, but it wouldn't hurt to produce a slightly more informative error message, e.g. 'Camera.ADOffset is required to load', if it is actually a hard requirement.

```
Traceback (most recent call last):
  File "/home/gs519/anaconda2/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16763, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/gs519/code/python-microscopy/PYME/DSView/dsviewer.py", line 423, in LoadData
    im = ImageStack(filename=args[0], queueURI=options.queueURI, mdh=options.metadata)
  File "/home/gs519/code/python-microscopy/PYME/IO/image.py", line 224, in __init__
    self.Load(filename, prompt=load_prompt)
  File "/home/gs519/code/python-microscopy/PYME/IO/image.py", line 964, in Load
    self._loadh5(filename)
  File "/home/gs519/code/python-microscopy/PYME/IO/image.py", line 445, in _loadh5
    MetaData.fillInBlanks(self.mdh, self.dataSource)
  File "/home/gs519/code/python-microscopy/PYME/Analysis/MetaData.py", line 246, in fillInBlanks
    md.setEntry('Camera.ADOffset', numpy.median(numpy.array([dataSource.getSlice(i) for i in range(0, 10)]).ravel()))
  File "/home/gs519/code/python-microscopy/PYME/IO/DataSources/HDFDataSource.py", line 65, in getSlice
    return self.h5File.root.ImageData[ind, :,:]
  File "/home/gs519/anaconda2/lib/python2.7/site-packages/tables/array.py", line 661, in __getitem__
    startl, stopl, stepl, shape = self._interpret_indexing(key)
  File "/home/gs519/anaconda2/lib/python2.7/site-packages/tables/array.py", line 407, in _interpret_indexing
    raise IndexError("Index out of range")
IndexError: Index out of range
```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

It's not a hard requirement - this is a bug in the fall-back code which tries to estimate ADOffset if it isn't provided. It is however important for localisation analysis. We should probably move this fall back logic to the LMAnalysis plugin (i.e. make h5 loading independent of setting up for localisation). There's currently an implicit assumption that you are going to want to run localization analysis on anything saved as h5.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Just ran into this again \(couldn’t save as tif thanks to xml bytes business\) and wanted to save a single frame.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Fixed by making fillInBlanks work for nFrames < 10

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

fixed
