### ISSUE TITLE
[BUG] multiview calibration generation breaking on delaunay dimensionality issue

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#757]
**Describe the bug**
```
 Error whilst running Corrections>Multiview>Calibrate Shifts
==============================================
python-microscopy=20.12.10
python=3.6.9, platform=linux
numpy=1.16.5, wx=4.0.4 gtk2 (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "/home/smeagol/code/python-microscopy/PYME/ui/progress.py", line 107, in func
    return fcn(*args, **kwargs)
  File "/home/smeagol/code/python-microscopy/PYME/LMVis/Extras/multiviewMapping.py", line 205, in OnCalibrateShifts
    sm = calibration_module.apply_simple(self.pipeline.selectedDataSource)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 206, in apply_simple
    return self.apply(*args, **kwargs)[next(iter(self.outputs))]
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 185, in apply
    self.execute(namespace)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/multiview.py", line 365, in execute
    dy_err[ii - 1, :])
  File "/home/smeagol/code/python-microscopy/PYME/Analysis/points/twoColour.py", line 265, in genShiftVectorFieldQ
    wonky = findWonkyVectors(nx, ny, nsx, nsy, tol=2*err_sx.mean())
  File "/home/smeagol/code/python-microscopy/PYME/Analysis/points/twoColour.py", line 411, in findWonkyVectors
    T = tri.Triangulation(x,y)
  File "/home/smeagol/miniconda3/lib/python3.6/site-packages/matplotlib/tri/triangulation.py", line 54, in __init__
    self.triangles, self._neighbors = _qhull.delaunay(x, y)
ValueError: x and y arrays must have a length of at least 3
```

**To Reproduce**
1. take multiview localizations
2. fold it
3. calibrate shifts
4. see error

**Comment by barentine** [comment]
hmm, a simple test recipe works fine
```
import os
from PYME.recipes.base import ModuleCollection
from PYME.recipes import multiview, localisations

recipe = ModuleCollection()
recipe.loadInput('pyme-cluster:///Bergamot/2021_1_7/000/analysis/reg.h5r')

recipe.add_module(localisations.Pipelineify(recipe))
recipe.add_module(multiview.Fold(recipe, input_name='Localizations'))
recipe.add_module(multiview.CalibrateShifts(recipe))

recipe.execute()

```

**Comment by barentine** [comment]
running with the full pipeline recipe demonstrates the default search radius is too small after filtering on error_x/y -> probably time to realign the instrument
