### ISSUE TITLE
possible gcc version issue for gauss cmodels

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#76]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/76) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

After what appears to be a successful installation with gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0

```Python

======================================================================
ERROR: localization.test_localization_algorithms.test_LatGaussFitFR
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gs519/anaconda2/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/gs519/code/python-microscopy/tests/PYME/localization/test_localization_algorithms.py", line 36, in test_LatGaussFitFR
    tj.runTests(nTests=100)
  File "/home/gs519/code/python-microscopy/PYME/localization/Test/fitTestJigWC.py", line 79, in runTests
    self.fitMod = __import__('PYME.localization.FitFactories.' + self.fitModule, fromlist=['PYME', 'localization', 'FitFactories']) #import our fitting module
  File "/home/gs519/code/python-microscopy/PYME/localization/FitFactories/LatGaussFitFR.py", line 28, in <module>
    from PYME.localization.cModels.gauss_app import genGauss,genGaussJac, genGaussJacW
  File "/home/gs519/code/python-microscopy/PYME/localization/cModels/__init__.py", line 24, in <module>
    from .gauss_app import *
ImportError: /home/gs519/code/python-microscopy/PYME/localization/cModels/gauss_app.so: undefined symbol: _ZGVbN2v___exp_finite
```

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Ugh - haven't actually tested on Ubuntu > 16.04 yet. This would be super annoying as there is no easy way to manage libc dependencies within conda.

That said, I'm pretty sure we link statically against libc so this shouldn't be an issue.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Just double checked and we do statically link to libgcc, which means that this really shouldn't be a problem. 

Although, looking a bit deeper, exp might be in libm, not libgcc. I guess we could statically link that too and see if it helped. It's frustrating in any case. 

Another explanation would be if continuum have started using something weird (e.g. clang) to compile the anaconda python binary.

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Thanks @david_baddeley . I'd tried that a couple of times but I don't think it was actually trying to recompile (had to remove the .so and try again). Now it works if I specify the -lm linker arg, see PR #229

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Would seem to be resolved by specifically linking to maths libraries with `-lm` linker switch
