### ISSUE TITLE
initializing dh5view with PYMECLUSTER:///rest/of/path tries to open a bioformats data source

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#8]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/8) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

aeb85@Omaha:~$ dh5view PYMECLUSTER:///Spooling_test/072616ROI00094
/home/aeb85/anaconda2/lib/python2.7/site-packages/matplotlib/cbook.py:137: MatplotlibDeprecationWarning: The matplotlib.delaunay module was deprecated in version 1.4. Use matplotlib.tri.Triangulation instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
Starting main loop
Loading data
filename == PYMECLUSTER:///Spooling_test/072616ROI00094
Bioformats:loading data
/home/aeb85/PYMEData/PYMECLUSTER:///Spooling_test/072616ROI00094
Traceback (most recent call last):
  File "/home/aeb85/anaconda2/lib/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py", line 16763, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/DSView/dsviewer.py", line 395, in LoadData
    im = ImageStack(filename=args[0], queueURI=options.queueURI, mdh=options.metadata)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/image.py", line 138, in __init__
    self.Load(filename)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/image.py", line 793, in Load
    self.LoadBioformats(filename)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/image.py", line 688, in LoadBioformats
    self.dataSource = BioformatsDataSource.DataSource(filename, None)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/DataSources/BioformatsDataSource.py", line 97, in __init__
    self.bff = bioformats.ImageReader(filename)
  File "/home/aeb85/anaconda2/lib/python2.7/site-packages/bioformats/formatreader.py", line 626, in __init__
    path)
IOError: [Errno 2] The file, "PYMECLUSTER:///Spooling_test/072616ROI00094", does not exist.: 'PYMECLUSTER:///Spooling_test/072616ROI00094'

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Bioformats is the fallback for anything which it doesn't understand. the error here is the URI for the cluster, which is PYME-CLUSTER://<clustername>/path/to/file

(sorry about leading you astray here last night)

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

Hi David,

No problem at all. Before I saw this I submitted a pull request to change PYME-CLUSTER to PYMECLUSTER, which I believe is the argument we use in LoadClusterPZF. Feel free to decline the request of course if we should be using PYME-CLUSTER

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

image.load and HTTPSpooler both use PYME-CLUSTER, I don't see any reason to
change it
