### ISSUE TITLE
[BUG] PYMEImage > Export Cropped failing on multicolor h5

### ISSUE THREAD

**Issue by barentine** [python-microscopy/python-microscopy#833]
**To Reproduce**
1. open a multichannel h5 file in PYMEImage
2. Click on File > Export Cropped
3. this stack is [1024, 1024, 1681, 3], I filled in
[256, 768] for x and y and left z/t at the default of 0, 1681. there is no C in the dialog
4. Choose to save to an h5
5.
```
Traceback (most recent call last):
  File "/Users/Andrew/code/python-microscopy/PYME/DSView/dsviewer.py", line 347, in OnExport
    self.image.Save(crop = True, roi=roi)
  File "/Users/Andrew/code/python-microscopy/PYME/IO/image.py", line 1127, in Save
    dataExporter.CropExportData(self.data, roi, self.mdh, self.events, self.seriesName)
  File "/Users/Andrew/code/python-microscopy/PYME/IO/dataExporter.py", line 575, in CropExportData
    exp.Export(data, filename, dlg.GetXSlice(), dlg.GetYSlice(), dlg.GetZSlice(),mdh, events, origName)
  File "/Users/Andrew/code/python-microscopy/PYME/IO/dataExporter.py", line 91, in Export
    xSize, ySize = data[xslice, yslice, 0].shape[:2]
  File "/Users/Andrew/code/python-microscopy/PYME/IO/DataSources/BaseDataSource.py", line 137, in __getitem__
    col_indices =  range(*keys[3].indices(self.shape[3]))
IndexError: list index out of range

```

**Comment by barentine** [comment]
thank you, David!
