### ISSUE TITLE
traits errors when batching analysis in bakeshop

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#87]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/87) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

```
Exception occurred in traits notification handler for object: <PYME.recipes.processing.StatisticsByFrame object at 0x7f0919ec6830>, trait: input_name, old value: input, new value: with_metadata
Traceback (most recent call last):
  File "/home/smeagol/anaconda2/envs/py36/lib/python3.6/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/smeagol/anaconda2/envs/py36/lib/python3.6/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 78, in invalidate_parent
    if self._invalidate_parent and not self.__dict__.get('_parent', None) is None:
AttributeError: 'StatisticsByFrame' object has no attribute '_invalidate_parent'
```

‌

```
Traceback (most recent call last):
  File "/home/smeagol/anaconda2/envs/py36/lib/python3.6/site-packages/traits/trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "/home/smeagol/anaconda2/envs/py36/lib/python3.6/site-packages/traits/trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "/home/smeagol/code/python-microscopy/PYME/recipes/base.py", line 78, in invalidate_parent
    if self._invalidate_parent and not self.__dict__.get('_parent', None) is None:
AttributeError: 'HDFOutput' object has no attribute '_invalidate_parent'
```

Not sure how problematic this error actually is yet.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

Hmm - this is really odd - the attribute is in ModuleBase - i.e. it should be there. Is this on a recently updated version \(I’m wondering if somehow you’ve got old .pyc files being used, or somehow have different installs getting confused\). Only thing I can think of is to delete base.pyc and try again.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

@{AndrewBarentine} Are you still running into this?

**Comment by David-Baddeley** [comment]
**Original comment by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

I haven’t noticed it for a bit but Dirk did in his email:

‌

```
Exception occurred in traits notification handler for object: <nep_fitting.recipe_modules.nep_fits.FitProfiles object at 0x000000001749E888>, trait: outputName, old value: fit_results, new value: output
Traceback (most recent call last):
  File "C:\Users\pcoffice62\.conda\envs\PYME\lib\site-packages\traits\trait_notifiers.py", line 591, in _dispatch_change_event
    self.dispatch(handler, *args)
  File "C:\Users\pcoffice62\.conda\envs\PYME\lib\site-packages\traits\trait_notifiers.py", line 553, in dispatch
    handler(*args)
  File "C:\Users\pcoffice62\.conda\envs\PYME\lib\site-packages\PYME\recipes\base.py", line 78, in invalidate_parent
    if self._invalidate_parent and not self.__dict__.get('_parent', None) is None:
AttributeError: 'FitProfiles' object has no attribute '_invalidate_parent'
```

‌

**Comment by zacsimile** [comment]
Is this still an issue @barentine?

**Comment by barentine** [comment]
I haven't seen it in quite some time - sorry I didn't include relevant traits versions in the initial report. I think it's probably OK to close this and simply re-open if we run into it again on current versions of traits/traitui/PYME
