### ISSUE TITLE
dh5view export fails to detect file type when no extension given

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#9]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/9) by Andrew Barentine (Bitbucket: [AndrewBarentine](https://bitbucket.org/AndrewBarentine), ).**

----------------------------------------

```
#!traceback

Traceback (most recent call last):
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/DSView/dsviewer.py", line 295, in OnSave
    self.image.Save()
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/image.py", line 824, in Save
    self.filename = dataExporter.ExportData(self.data, self.mdh, self.events, filename=filename)
  File "/home/aeb85/PycharmProjects/python-microscopy/PYME/IO/dataExporter.py", line 492, in ExportData
    raise RuntimeError('No exporter found for %s files')
RuntimeError: No exporter found for %s files
```

when exporting files, dh5view currently uses the extension to determine file type, ignoring the dropdown menu in the GUI.

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

fixed in be2ed35 by testing for an extension
