### ISSUE TITLE
[BUG] HDF5 error when spooling on Ubuntu 20.04.1 

### ISSUE THREAD

**Issue by adrianhollow** [python-microscopy/python-microscopy#903]
**Describe the bug**
Using the option "Spool to h5 on cluster" in PYMEAcquire leads to file error on the cluster. Appears cluster thread cannot open the h5 file for some reason.

**To Reproduce**
1. Start PYMEClusterOfOne and PYMEAcquire.
2. Select `simul488.py` protocol, "Z stepped" and "Spool to h5 on cluster"
3. Click "Start"

**Expected behavior**
Successful save to h5 on the cluster.

**Screenshots**
![Screenshot from 2021-02-27 15-06-20](https://user-images.githubusercontent.com/43847198/109389666-9702a200-790d-11eb-9ce9-5b875749c187.png)
Stacktrace from PYMECluster:
```
----------------------------------------
DEBUG:root:pytables open call: /home/tphan/PYMEData/tphan/2021_2_27/27_2_series_A.h5
HDF5-DIAG: Error detected in HDF5 (1.10.4) thread 139755500361472:
  #000: H5F.c line 509 in H5Fopen(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #001: H5Fint.c line 1400 in H5F__open(): unable to open file
    major: File accessibilty
    minor: Unable to open file
  #002: H5Fint.c line 1615 in H5F_open(): unable to lock the file
    major: File accessibilty
    minor: Unable to open file
  #003: H5FD.c line 1640 in H5FD_lock(): driver lock request failed
    major: Virtual File Layer
    minor: Can't update object
  #004: H5FDsec2.c line 941 in H5FD_sec2_lock(): unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'
    major: File accessibilty
    minor: Bad file ID accessed
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45646)
Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/server.py", line 646, in __init__
    super().__init__(*args, **kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/home/tphan/thesis/python-microscopy/PYME/cluster/HTTPDataServer.py", line 485, in do_GET
    f = self.send_head()
  File "/home/tphan/thesis/python-microscopy/PYME/cluster/HTTPDataServer.py", line 570, in send_head
    return self.list_h5(path)
  File "/home/tphan/thesis/python-microscopy/PYME/cluster/HTTPDataServer.py", line 657, in list_h5
    with h5File.openH5(path.rstrip('/').rstrip('\\')) as h5f:
  File "/home/tphan/thesis/python-microscopy/PYME/IO/h5File.py", line 29, in openH5
    h5rFile.file_cache[key] = H5File(filename, mode)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/h5rFile.py", line 68, in __init__
    self._h5file = tables.open_file(filename, mode)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/tables/file.py", line 315, in open_file
    return File(filename, mode, title, root_uep, filters, **kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/tables/file.py", line 778, in __init__
    self._g_new(filename, mode, **params)
  File "tables/hdf5extension.pyx", line 492, in tables.hdf5extension.File._g_new
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5F.c", line 509, in H5Fopen
    unable to open file
  File "H5Fint.c", line 1400, in H5F__open
    unable to open file
  File "H5Fint.c", line 1615, in H5F_open
    unable to lock the file
  File "H5FD.c", line 1640, in H5FD_lock
    driver lock request failed
  File "H5FDsec2.c", line 941, in H5FD_sec2_lock
    unable to lock file, errno = 11, error message = 'Resource temporarily unavailable'

End of HDF5 error back trace

Unable to open/create file '/home/tphan/PYMEData/tphan/2021_2_27/27_2_series_A.h5'
----------------------------------------
```

Stacktrace from PYMEAquire:
```

'http://127.0.0.1:43709/__aggregate_h5/tphan/2021_2_27/27_2_series_A.h5/metadata.json'
ERROR:PYME.IO.clusterIO:Error writing to 127.0.0.1, trying another server for 14 remaining files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1172, in put_files
    s.sendall(header)
BrokenPipeError: [Errno 32] Broken pipe
ERROR:PYME.IO.clusterIO:Error writing to 127.0.0.1, trying another server for 14 remaining files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1172, in put_files
    s.sendall(header)
BrokenPipeError: [Errno 32] Broken pipe
ERROR:PYME.IO.clusterIO:Error writing to 127.0.0.1, trying another server for 14 remaining files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1172, in put_files
    s.sendall(header)
BrokenPipeError: [Errno 32] Broken pipe
...
ERROR:PYME.IO.clusterIO:Error writing to 127.0.0.1, trying another server for 14 remaining files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1172, in put_files
    s.sendall(header)
BrokenPipeError: [Errno 32] Broken pipe
ERROR:PYME.IO.clusterIO:Error writing to 127.0.0.1, trying another server for 18 remaining files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1172, in put_files
    s.sendall(header)
BrokenPipeError: [Errno 32] Broken pipe
ERROR:PYME.IO.clusterIO:Error writing to 127.0.0.1, trying another server for 14 remaining files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1172, in put_files
    s.sendall(header)
BrokenPipeError: [Errno 32] Broken pipe
INFO:numexpr.utils:Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
ERROR:PYME.IO.clusterIO:Error writing to 127.0.0.1, trying another server for 14 remaining files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1172, in put_files
    s.sendall(header)
BrokenPipeError: [Errno 32] Broken pipe
/home/tphan/miniconda3/envs/mypyme/lib/python3.7/_collections_abc.py:702: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  return len(self._mapping)
/home/tphan/miniconda3/envs/mypyme/lib/python3.7/_collections_abc.py:720: MatplotlibDeprecationWarning: The global colormaps dictionary is no longer considered public API.
  yield from self._mapping
Starting main loop
Loading data
filename == PYME-CLUSTER:///tphan/2021_2_27/27_2_series_A.h5
ERROR:PYME.IO.clusterIO:Error writing to 127.0.0.1, trying another server for 34 remaining files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1172, in put_files
    s.sendall(header)
BrokenPipeError: [Errno 32] Broken pipe
ERROR:root:Exception whilst putting files
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1037, in _read_status
    [version, status, reason] = line.split(None, 2)
ValueError: not enough values to unpack (expected 3, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/Acquire/HTTPSpooler.py", line 196, in _queuePoll
    clusterIO.put_files(files, serverfilter=self.clusterFilter)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1194, in put_files
    status, reason, msg = _parse_response(fp)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1054, in _parse_response
    version, status, reason = _read_status(fp)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1039, in _read_status
    [version, status] = line.split(None, 1)
ValueError: not enough values to unpack (expected 2, got 0)
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1037, in _read_status
    [version, status, reason] = line.split(None, 2)
ValueError: not enough values to unpack (expected 3, got 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tphan/thesis/python-microscopy/PYME/Acquire/HTTPSpooler.py", line 196, in _queuePoll
    clusterIO.put_files(files, serverfilter=self.clusterFilter)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1194, in put_files
    status, reason, msg = _parse_response(fp)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1054, in _parse_response
    version, status, reason = _read_status(fp)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 1039, in _read_status
    [version, status] = line.split(None, 1)
ValueError: not enough values to unpack (expected 2, got 0)

'http://127.0.0.1:43709/__aggregate_h5/tphan/2021_2_27/27_2_series_A.h5/final_metadata.json'
'http://127.0.0.1:33551/__aggregate_h5/tphan/2021_2_27/27_2_series_A.h5/events.json'
Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/Acquire/ui/HDFSpoolFrame.py", line 512, in OnBStopSpoolingButton
    self.spoolController.StopSpooling()
  File "/home/tphan/thesis/python-microscopy/PYME/Acquire/SpoolController.py", line 500, in StopSpooling
    self.spooler.StopSpool()
  File "/home/tphan/thesis/python-microscopy/PYME/Acquire/Spooler.py", line 177, in StopSpool
    self.finalise() #TODO - should this be before we send the onStopSpool signal?
  File "/home/tphan/thesis/python-microscopy/PYME/Acquire/HTTPSpooler.py", line 269, in finalise
    self.clusterFilter, timeout=10)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 986, in put_file
    r = s.put(url, data=data, timeout=timeout)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 602, in put
    return self.request('PUT', url, data=data, **kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
WARNING:PYME.Acquire.frameWrangler:Not keeping up with camera, giving up with 19 frames still in buffer

ERROR:PYME.IO.clusterIO:Timeout on listing directory
Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 248, in _listSingleDir
    r = s.get(url, timeout=timeout)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
INFO:PYME.IO.clusterIO:0 retries left
Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 706, in urlopen
    chunked=chunked,
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/urllib3/connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 1369, in getresponse
    response.begin()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/wx/core.py", line 3259, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/tphan/thesis/python-microscopy/PYME/DSView/dsviewer.py", line 450, in LoadData
    im = ImageStack(filename=args[0], queueURI=options.queueURI, mdh=options.metadata)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/image.py", line 238, in __init__
    self.Load(filename, prompt=load_prompt, haveGUI=self.haveGUI)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/image.py", line 1036, in Load
    self._loadClusterPZF(filename)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/image.py", line 503, in _loadClusterPZF
    self.dataSource = ClusterPZFDataSource.DataSource(filename)
  File "/home/tphan/thesis/python-microscopy/PYME/IO/DataSources/ClusterPZFDataSource.py", line 62, in __init__
    self._getNumFrames()
  File "/home/tphan/thesis/python-microscopy/PYME/IO/DataSources/ClusterPZFDataSource.py", line 65, in _getNumFrames
    frameNames = [f for f in clusterIO.listdir(self.sequenceName, self.clusterfilter) if f.endswith('.pzf')]
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 438, in listdir
    return sorted(listdirectory(dirname, serverfilter).keys())
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 426, in listdirectory
    listings = _pool.map(_listSingleDir, urls)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/tphan/thesis/python-microscopy/PYME/IO/clusterIO.py", line 248, in _listSingleDir
    r = s.get(url, timeout=timeout)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/tphan/miniconda3/envs/mypyme/lib/python3.7/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```

**Platform (please complete the following information - or copy-paste from error dialog if shown):**
 - OS: Ubuntu 20.04.1 LTS
 - Python version: 3.7.9
 - numpy version: 1.19.2
 - pytables version: 3.6.1

**Additional context**

**Comment by David-Baddeley** [comment]
I suspect this is a HDF library issue, likely specific to your version of linux and / or the installed version of libhdf5. Notably **I cannot reproduce on Ubuntu 18.04.5, Python 3.7.7** (or on OSX).

**Comment by David-Baddeley** [comment]
@adrianhollow - Could you double check that this is reproducible on your system. 

The alternative option to a libhdf5 bug is that, e.g., there had been a previous attempt to write to that file which had resulted in a hard failure (e.g. via a segfault) leaving a stale HDF lock in place. This would be expected to happen very rarely.

**Comment by adrianhollow** [comment]
Curiously, I can't reproduce this error today. I'm not aware of changing anything except switching git branches, though I took careful note that the error only appeared when I pulled the latest commits from `master`. I'll check if I made any other changes and try again, but it seems very strange to me.

**Comment by David-Baddeley** [comment]
The other option is a race condition when the file timed out and was closed followed by a write which tried to open it before closing had fully finished.

**Comment by David-Baddeley** [comment]
calling this stale
