### ISSUE TITLE
Recipe SVG display in cluster UI broken on py3

### ISSUE THREAD

**Issue by David-Baddeley** [python-microscopy/python-microscopy#96]
**[Original report](https://bitbucket.org/david_baddeley/python-microscopy/issue/96) by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

from @{AndrewBarentine} on py3 super-issue

‌

recipe svg render in clusterUI, standalone view, seems to have regressed in Py3. Run’s fine on py2 but I get the following on py3 with the same recipe. Possibly a dependencyGraph issue?

```
/home/smeagol/code/python-microscopy/PYME/recipes/base.py:574: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  l = yaml.load(data)
Internal Server Error: /recipes/svg/
Traceback (most recent call last):
  File "/home/smeagol/anaconda2/envs/py36/lib/python3.6/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/home/smeagol/anaconda2/envs/py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/smeagol/anaconda2/envs/py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/smeagol/anaconda2/envs/py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/smeagol/code/python-microscopy/PYME/cluster/clusterUI/recipes/views.py", line 85, in view_svg
    svg = recipeLayout.to_svg(recipe.dependancyGraph())
  File "/home/smeagol/code/python-microscopy/PYME/recipes/recipeLayout.py", line 428, in to_svg
    vb = dwg.viewbox(xmn - .5, ymn -.5, xmx + 2, ymx + 2)
UnboundLocalError: local variable 'xmn' referenced before assignment
```

‌

‌

**Comment by David-Baddeley** [comment]
**Original comment by David Baddeley (Bitbucket: [david_baddeley](https://bitbucket.org/david_baddeley), ).**

----------------------------------------

What makes you suspect a dependency graph issue?

Error almost certainly comes from  failure to allocate `xmn` etc … in lines 418:425

‌

```python
ipsv = np.array(node_positions.values())
    try:
        xmn, ymn = ipsv.min(0)
        xmx, ymx = ipsv.max(0)

        #self.ax.set_ylim(ymn - 1, ymx + 1)
        #self.ax.set_xlim(xmn - .5, xmx + .7)
    except ValueError:
        pass
```

‌

which probably stems from an error in the node\_positions

Questions:

* Is there anything in the recipe, or does this just happen for empty recipes?
* what is in node\_postitions, etc …
* why are lines 418:425 in a try:catch block anyway?

‌

**Comment by barentine** [comment]
Running into this again while testing django 1.11 functionality.

Recipe opens fine in bakeshop
```
- localisations.AddPipelineDerivedVars:
    inputDriftResults: ‘’
    inputEvents: ‘’
    inputFitResults: FitResults
    outputLocalizations: localizations
- localisations.DensityMapping:
    inputLocalizations: filtered
    jitterVariable: neighbourDistances
    outputImage: output
    pixelSize: 20.0
    renderingModule: Jittered Triangulation
    zBounds:
    - 0.0
    - 0.0
- tablefilters.FilterTable:
    filters:
      A:
      - 0
      - 10000
      error_x:
      - 0
      - 30
      error_y:
      - 0
      - 30
    inputName: clumped
    outputName: filtered
- multiview.Fold:
    input_name: localizations
    output_name: folded
- multiview.FindClumps:
    input_name: registered
    output_name: clumped
```

but throws when opening the rendering the svg for clusterUI

```
Internal Server Error: /recipes/svg/
Traceback (most recent call last):
  File "/Users/Andrew/miniconda3/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/Andrew/miniconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/Andrew/miniconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Andrew/miniconda3/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Andrew/code/python-microscopy/PYME/cluster/clusterUI/recipes/views.py", line 85, in view_svg
    svg = recipeLayout.to_svg(recipe.dependancyGraph())
  File "/Users/Andrew/code/python-microscopy/PYME/recipes/recipeLayout.py", line 428, in to_svg
    vb = dwg.viewbox(xmn - .5, ymn -.5, xmx + 2, ymx + 2)
UnboundLocalError: local variable 'xmn' referenced before assignment
```

Will look into `node_positions`, etc.

**Comment by barentine** [comment]
Issue is with dict_values not being a list in python 3, so `np.array(node_positions.values())` returns a funky array:
```
array(dict_values([(0, -0.04999999986450199), (0, 0.05000000013549802), (1, 0.05000000013549802), (2, 0.05000000013549802), (3, 0.05000000013549802), (4, 0.05000000013549802), (5, 0.02500000013549802), (6, 0.02500000013549802), (7, 0.02500000013549802), (8, 0.02500000013549802), (9, 0.02500000013549802), (10, 0.02500000013549802)]),
      dtype=object)
```

Will submit PR

**Comment by barentine** [comment]
This can be closed, @David-Baddeley

**Comment by zacsimile** [comment]
I think this can be closed.
