### ISSUE TITLE
[BUG] CopyOnWriteMDHandler does not expose method interface - causes errors downstream of LMAnalyser code

### ISSUE THREAD

**Issue by csoeller** [python-microscopy/python-microscopy#976]
**Describe the bug**
In using `Test this Frame` from LMAnalyser getting multiple errors when using FitInfo with, e.g., `SplitterFitInterpBNR`

**To Reproduce**
1. Open `h5` series
2. use `SplitterFitInterpBNR` with appropriate data set
3. Press `Test This Frame`
4. Select event
5. See error:

```
Traceback (most recent call last):
  File "/Users/csoe002/Documents/src/PYME-src/pyme-py3/PYME/DSView/modules/LMAnalysis.py", line 819, in update
    self.fitInf.UpdateDisp(self.view.PointsHitTest())
  File "/Users/csoe002/Documents/src/PYME-src/pyme-py3/PYME/DSView/fitInfo.py", line 161, in UpdateDisp
    self.fitViewPan.draw(index)
  File "/Users/csoe002/Documents/src/PYME-src/pyme-py3/PYME/DSView/fitInfo.py", line 435, in draw
    imf = fitMod.genFitImage(fri, self.mdh).squeeze()
  File "/Users/csoe002/Documents/src/PYME-src/pyme-py3/PYME/localization/FitFactories/SplitterFitInterpBNR.py", line 183, in genFitImage
    im = InterpFitFactory._evalModel(np.array(list(fitResults['fitResults'])), metadata, xslice, yslice, ratio, x_, y_)[0]
  File "/Users/csoe002/Documents/src/PYME-src/pyme-py3/PYME/localization/FitFactories/SplitterFitInterpBNR.py", line 211, in _evalModel
    estimatorModule = md.Analysis.EstimatorModule
AttributeError: 'CopyOnWriteMDHandler' object has no attribute 'Analysis'
```

**Expected behavior**
Should work smoothly.

**Platform (please complete the following information - or copy-paste from error dialog if shown):**

- python-microscopy=21.03.10
- python=3.7.6, platform=darwin
- numpy=1.19.2, wx=4.0.4 osx-cocoa (phoenix) wxWidgets 3.0.5

**Additional context**

Carried out a few tests in `dh5view` shell. Whereas the original `image.mdh` (`PYME.IO.MetaDataHandler.NestedClassMDHandler`) exposes all entries via the method interface, `mdhc` (`PYME.IO.MetaDataHandler.CopyOnWriteMDHandler`) does not seem to do this which leads to the downstream errors. I do not know what the exact class magic is that makes or breaks this, so would appreciate some pointers. It is probably a simple fix.

```python
from PYME.IO.MetaDataHandler import CopyOnWriteMDHandler
mdhc = CopyOnWriteMDHandler(image.mdh)

mdhc.Analysis
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AttributeError: 'CopyOnWriteMDHandler' object has no attribute 'Analysis'

dir(mdhc)
['GetSimpleString', 'WriteSimple', '_MutableMapping__marker', '__abstractmethods__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__setitem__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', '_cache', '_orig_md', 'clear', 'copyEntriesFrom', 'get', 'getEntry', 'getEntryNames', 'getOrDefault', 'items', 'keys', 'mergeEntriesFrom', 'pop', 'popitem', 'setEntry', 'setdefault', 'tformat', 'to_JSON', 'update', 'values', 'voxelsize_nm']

mdhc.voxelsize_nm
VoxelSize(x=110.0, y=110.0, z=50.0)

dir(image.mdh)
['AcquiringUser', 'ActiveCamera', 'Analysis', 'Camera', 'DataFileID', 'EndTime', 'EstimatedLaserOnFrameNo', 'GetSimpleString', 'Lasers', 'NikonTi', 'PRI', 'PSFFile', 'Positioning', 'Protocol', 'Sample', 'Splitter', 'StackSettings', 'StartTime', 'WriteSimple', '_MutableMapping__marker', '__abstractmethods__', '__class__', '__contains__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__setitem__', '__sizeof__', '__slotnames__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', 'chroma', 'clear', 'copyEntriesFrom', 'get', 'getEntry', 'getEntryNames', 'getOrDefault', 'imageID', 'items', 'keys', 'mergeEntriesFrom', 'pop', 'popitem', 'setEntry', 'setdefault', 'tIndex', 'tformat', 'to_JSON', 'update', 'values', 'voxelsize', 'voxelsize_nm']
```

**Comment by David-Baddeley** [comment]
The long term plan is to deprecate attribute-based access in favour of dictionary like access (i.e. it's a bug in `SplitterFitInterpBNR`). Hitting all the attribute style usages at once is likely to be very hard, so a reasonable short-term approach is likely to be:

a) implement  `__getattr__` on the `MDHandlerBase` to  permit attribute based access for all metadata handlers
b) make this raise/flag a `DeprecationWarning`
